### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Gamofinn** [RockinChaos/ItemJoin#103]
Hi, I am getting this error:
`[12:41:41 ERROR]: Error occurred while enabling ItemJoin v3.9.3 (Is it up to date?)
java.lang.NullPointerException
	at me.RockinChaos.itemjoin.utils.Econ.enableEconomy(Econ.java:15) ~[?:?]
	at me.RockinChaos.itemjoin.ItemJoin.onEnable(ItemJoin.java:52) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[server.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [server.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [server.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:376) [server.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:326) [server.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:421) [server.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:382) [server.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:337) [server.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272) [server.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:544) [server.jar:git-Spigot-3fb9445-6e3cec8]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]`

**Comment by RockinChaos** [comment]
This looks to be an issue with vault. Are you running vault and if your not makesure vault is set to false in itemjoins configyml

Can you post your items and config .yml in a pastebin.com send it please?

**Comment by Gamofinn** [comment]
Ok, I think my vault is broken because some other plugins are not sensing it either. Have disabled it and it is now working. Thanks!

**Comment by RockinChaos** [comment]
Sweet, let me know if you ever need help with anything else.
