### ISSUE TITLE
NoClassDefFoundError: org/bukkit/craftbukkit/libs/jline/internal/InputStreamReader

### ISSUE THREAD

**Issue by mibby** [RockinChaos/ItemJoin#104]
ItemJoin v3.9.3
Paper dev 1121 (Spigot 1.12)

@RockinChaos ItemJoin fails to start-up for me on 1.12.

Could this be caused by Paper's improved console implementation in this commit https://github.com/PaperMC/Paper/commit/de2af506f35c415345189814a08f867a70f76a4b? @Minecrell @Zbob750 

```
[10:00:14] [Server thread/ERROR]: Error occurred while enabling ItemJoin v3.9.3 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/libs/jline/internal/InputStreamReader
	at me.RockinChaos.itemjoin.ItemJoin.onEnable(ItemJoin.java:50) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.jar:git-Paper-1121]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12.jar:git-Paper-1121]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [patched_1.12.jar:git-Paper-1121]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:378) [patched_1.12.jar:git-Paper-1121]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:328) [patched_1.12.jar:git-Paper-1121]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:441) [patched_1.12.jar:git-Paper-1121]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:402) [patched_1.12.jar:git-Paper-1121]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:340) [patched_1.12.jar:git-Paper-1121]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:283) [patched_1.12.jar:git-Paper-1121]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:615) [patched_1.12.jar:git-Paper-1121]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92) ~[patched_1.12.jar:git-Paper-1121]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched_1.12.jar:git-Paper-1121]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_131]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_131]
	... 12 more
[10:00:14] [Server thread/INFO]: [ItemJoin] Disabling ItemJoin v3.9.3
[10:00:14] [Server thread/ERROR]: Error occurred while disabling ItemJoin v3.9.3 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/libs/jline/internal/InputStreamReader
	at me.RockinChaos.itemjoin.ItemJoin.onDisable(ItemJoin.java:63) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[patched_1.12.jar:git-Paper-1121]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:344) [patched_1.12.jar:git-Paper-1121]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:320) [patched_1.12.jar:git-Paper-1121]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [patched_1.12.jar:git-Paper-1121]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:378) [patched_1.12.jar:git-Paper-1121]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:328) [patched_1.12.jar:git-Paper-1121]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:441) [patched_1.12.jar:git-Paper-1121]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:402) [patched_1.12.jar:git-Paper-1121]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:340) [patched_1.12.jar:git-Paper-1121]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:283) [patched_1.12.jar:git-Paper-1121]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:615) [patched_1.12.jar:git-Paper-1121]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92) ~[patched_1.12.jar:git-Paper-1121]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched_1.12.jar:git-Paper-1121]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_131]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_131]
	... 13 more
```

**Comment by Zbob750** [comment]
Yes it could, and is. Exact same issue as PaperMC/Paper#733.
Another plugin using an internal CraftBukkit library instead of updating to the supported API calls.

**Comment by RockinChaos** [comment]
Has to do with the updater on ItemJoin. Should be fixed in the latest snapshot; http://jenkins.craftationgaming.com:8080/job/ItemJoin/5/

**Comment by mibby** [comment]
Using the latest snapshot does seem to work, thanks. :)
