### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Waffles2112** [RockinChaos/ItemJoin#107]
[04:41:12 WARN]: [ItemJoin] Task #5368 for ItemJoin v3.9.3 generated an exception
java.lang.NullPointerException
        at me.RockinChaos.itemjoin.Listeners.JoinItem.FirstJoin.setJoinItems(FirstJoin.java:52) ~[?:?]
        at me.RockinChaos.itemjoin.Listeners.JoinItem.JoinItem$2.run(JoinItem.java:78) ~[?:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.11.2.jar:git-Paper-1101]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356) [patched_1.11.2.jar:git-Paper-1101]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:820) [patched_1.11.2.jar:git-Paper-1101]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.2.jar:git-Paper-1101]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:754) [patched_1.11.2.jar:git-Paper-1101]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:652) [patched_1.11.2.jar:git-Paper-1101]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]

happens when player join server/receives no items ._.

**Comment by RockinChaos** [comment]
Looks to be a configuration issue, can you please post your config and items.yml in a pastebin.com and send me the links?

**Comment by Waffles2112** [comment]
https://pastebin.com/fcdUnY1n
https://pastebin.com/BSAKmNCy

**Comment by RockinChaos** [comment]
Yeah it was a configuration issue, you defined your world "Big" under world-list but you didn't define any items for it, you have to rename the
world:
    items:

to
Big:
    items:

Here is a fixed items.yml you should see the change if you compare your's vs mine.
#// For every world listed in the world-list, you need to make a section for it. //#
https://pastebin.com/Vkt6gZKq

**Comment by Waffles2112** [comment]
thanks ye .3.
