### ISSUE TITLE
BungeeCord Error

### ISSUE THREAD

**Issue by Zukeow** [RockinChaos/ItemJoin#134]
Hello guys, I have this error with my BungeeCord (Fluctis hosting) the truth is not why it leaves, before I left another error but reset the config.yml and removed, but now I get this error that does not let me start the console, I really need help :(

16:14:38 [INFO] Using zlib based native compressor.
16:14:38 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.12-SNAPSHOT:fd67502:1259
16:14:38 [INFO] Not on Windows, attempting to use enhanced EpollEventLoop
16:14:38 [INFO] Epoll is working, utilising it!
16:14:38 [INFO] Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource())
16:14:38 [INFO] Discovered module: ModuleSpec(name=cmd_find, file=modules/cmd_find.jar, provider=JenkinsModuleSource())
16:14:38 [INFO] Discovered module: ModuleSpec(name=cmd_list, file=modules/cmd_list.jar, provider=JenkinsModuleSource())
16:14:38 [INFO] Discovered module: ModuleSpec(name=cmd_send, file=modules/cmd_send.jar, provider=JenkinsModuleSource())
16:14:38 [INFO] Discovered module: ModuleSpec(name=cmd_server, file=modules/cmd_server.jar, provider=JenkinsModuleSource())
16:14:38 [INFO] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource())
16:14:38 [INFO] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.12-SNAPSHOT:fd67502:1259 by SpigotMC
16:14:38 [INFO] Loaded plugin cmd_find version git:cmd_find:1.12-SNAPSHOT:fd67502:1259 by SpigotMC
16:14:38 [WARNING] Error enabling plugin MaxBans
java.lang.NoClassDefFoundError: org/bukkit/plugin/java/JavaPlugin
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:34)
at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:304)
at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:212)
at net.md_5.bungee.BungeeCord.start(BungeeCord.java:264)
at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.ClassNotFoundException: org.bukkit.plugin.java.JavaPlugin
at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:53)
at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 18 more
16:14:38 [INFO] Loaded plugin cmd_server version git:cmd_server:1.12-SNAPSHOT:fd67502:1259 by SpigotMC
16:14:38 [INFO] Loaded plugin cmd_alert version git:cmd_alert:1.12-SNAPSHOT:fd67502:1259 by SpigotMC
16:14:38 [INFO] Loaded plugin cmd_send version git:cmd_send:1.12-SNAPSHOT:fd67502:1259 by SpigotMC
16:14:38 [INFO] Loaded plugin cmd_list version git:cmd_list:1.12-SNAPSHOT:fd67502:1259 by SpigotMC
16:14:38 [WARNING] Forced host server pvp is not defined
16:14:38 [INFO] Enabled plugin reconnect_yaml version git:reconnect_yaml:1.12-SNAPSHOT:fd67502:1259 by SpigotMC
16:14:38 [INFO] Enabled plugin cmd_find version git:cmd_find:1.12-SNAPSHOT:fd67502:1259 by SpigotMC
16:14:38 [INFO] Enabled plugin cmd_server version git:cmd_server:1.12-SNAPSHOT:fd67502:1259 by SpigotMC
16:14:38 [INFO] Enabled plugin cmd_alert version git:cmd_alert:1.12-SNAPSHOT:fd67502:1259 by SpigotMC
16:14:38 [INFO] Enabled plugin cmd_send version git:cmd_send:1.12-SNAPSHOT:fd67502:1259 by SpigotMC
16:14:38 [INFO] Enabled plugin cmd_list version git:cmd_list:1.12-SNAPSHOT:fd67502:1259 by SpigotMC
16:14:38 [INFO] Listening on /0.0.0.0:25577
16:14:39 [INFO] §cCommand not found

**Comment by RockinChaos** [comment]
erm.. is this an issue with ItemJoin or just a general BungeeCord problem?
