### ISSUE TITLE
EventException moving between worlds

### ISSUE THREAD

**Issue by SlimeDog** [RockinChaos/ItemJoin#155]
Spigot 1.12.2
ItemJoin 4.7

IJ item brings up a navigation menu. Not sure exactly what transpired.
```
[16:40:19 ERROR]: Could not pass event PlayerInteractEvent to ItemJoin v4.7
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar-2018-01-10-0033:git-Spigot-109b080-bd30843]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar-2018-01-10-0033:git-Spigot-109b080-bd30843]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar-2018-01-10-0033:git-Spigot-109b080-bd30843]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar-2018-01-10-0033:git-Spigot-109b080-bd30843]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:235) [spigot-1.12.2.jar-2018-01-10-0033:git-Spigot-109b080-bd30843]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:202) [spigot-1.12.2.jar-2018-01-10-0033:git-Spigot-109b080-bd30843]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:198) [spigot-1.12.2.jar-2018-01-10-0033:git-Spigot-109b080-bd30843]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:989) [spigot-1.12.2.jar-2018-01-10-0033:git-Spigot-109b080-bd30843]
        at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:26) [spigot-1.12.2.jar-2018-01-10-0033:git-Spigot-109b080-bd30843]
        at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [spigot-1.12.2.jar-2018-01-10-0033:git-Spigot-109b080-bd30843]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar-2018-01-10-0033:git-Spigot-109b080-bd30843]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar-2018-01-10-0033:git-Spigot-109b080-bd30843]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar-2018-01-10-0033:git-Spigot-109b080-bd30843]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar-2018-01-10-0033:git-Spigot-109b080-bd30843]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar-2018-01-10-0033:git-Spigot-109b080-bd30843]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar-2018-01-10-0033:git-Spigot-109b080-bd30843]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.NullPointerException
        at me.RockinChaos.itemjoin.listeners.Placement.reAddItem(Placement.java:109) ~[?:?]
        at me.RockinChaos.itemjoin.listeners.Placement.onCountLock(Placement.java:52) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_151]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar-2018-01-10-0033:git-Spigot-109b080-bd30843]
        ... 18 more
```

**Comment by RockinChaos** [comment]
Can I see your items.yml? Pastebin.com link please?

**Comment by SlimeDog** [comment]
In PM. Let me know when you grab it, so I can remove it.

**Comment by RockinChaos** [comment]
Ermm.. PM where?

**Comment by RockinChaos** [comment]
The issue is that you have count-lock on an item that isn't a block or disposable item. 
Remove count-lock from the WATCH item and it should work fine.

I will have to add a check later that won't allow the code to continue if its not an item that you can "use" such as eat or place down.

**Comment by SlimeDog** [comment]
Welcome. Note that this changed with IJ 4.7. Thanks for the catch.
