### ISSUE TITLE
/itemjoin reload still not work in console 

### ISSUE THREAD

**Issue by anyecraft** [RockinChaos/ItemJoin#157]
![image](https://user-images.githubusercontent.com/32854951/34858192-cd4158b0-f789-11e7-87b4-61f1ac867b28.png)

**Comment by RockinChaos** [comment]
Somethings not right with your en-lang.yml.

Can you send me it via a pastebin.com link please?

**Comment by anyecraft** [comment]
`[11:14:38] [Server thread/WARN]: Unexpected exception while parsing console command "itemjoin reload"
org.bukkit.command.CommandException: Unhandled exception executing command 'itemjoin' in plugin ItemJoin v4.7
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.12.2.jar:git-Paper-1297]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.12.2.jar:git-Paper-1297]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:673) ~[patched_1.12.2.jar:git-Paper-1297]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:636) [patched_1.12.2.jar:git-Paper-1297]
	at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:464) [patched_1.12.2.jar:git-Paper-1297]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [patched_1.12.2.jar:git-Paper-1297]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1297]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1297]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.ClassCastException: com.destroystokyo.paper.console.TerminalConsoleCommandSender cannot be cast to org.bukkit.entity.Player
	at me.RockinChaos.itemjoin.utils.Language.sendEnglishMessage(Language.java:26) ~[ItemJoin.jar:?]
	at me.RockinChaos.itemjoin.utils.Language.getSendMessage(Language.java:16) ~[ItemJoin.jar:?]
	at me.RockinChaos.itemjoin.utils.Commands.onCommand(Commands.java:113) ~[ItemJoin.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.12.2.jar:git-Paper-1297]
	... 8 more
[11:19:08] [Server thread/WARN]: Unexpected exception while parsing console command "itemjoin reload"
org.bukkit.command.CommandException: Unhandled exception executing command 'itemjoin' in plugin ItemJoin v4.7
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.12.2.jar:git-Paper-1297]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.12.2.jar:git-Paper-1297]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:673) ~[patched_1.12.2.jar:git-Paper-1297]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:636) [patched_1.12.2.jar:git-Paper-1297]
	at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:464) [patched_1.12.2.jar:git-Paper-1297]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [patched_1.12.2.jar:git-Paper-1297]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1297]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1297]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.ClassCastException: com.destroystokyo.paper.console.TerminalConsoleCommandSender cannot be cast to org.bukkit.entity.Player
	at me.RockinChaos.itemjoin.utils.Language.sendEnglishMessage(Language.java:26) ~[ItemJoin.jar:?]
	at me.RockinChaos.itemjoin.utils.Language.getSendMessage(Language.java:16) ~[ItemJoin.jar:?]
	at me.RockinChaos.itemjoin.utils.Commands.onCommand(Commands.java:113) ~[ItemJoin.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.12.2.jar:git-Paper-1297]
	... 8 more`

en-lang.yml is default

**Comment by RockinChaos** [comment]
Interesting.. I can't seem to replicate this.

Can you try this and tell me if the error is resolved; http://ci.craftationgaming.com/job/ItemJoin/97/artifact/target/ItemJoin-4.8-SNAPSHOT.jar

**Comment by anyecraft** [comment]
The new version has solved this issue.

**Comment by RockinChaos** [comment]
Sweet, Seems to be an issue with paper, The snapshot is safe to use until v4.8 is fully released :)
