### ISSUE TITLE
IllegalArgumentException: bound must be positive

### ISSUE THREAD

**Issue by mibby** [RockinChaos/ItemJoin#173]
Assuming error is caused by https://github.com/RockinChaos/ItemJoin/commit/694ee9fe078db6f1a5ba692082a3933444ad0c50 with missing ```probability: #``` for items.

```
[04:53:29] [Server thread/WARN]: [ItemJoin] Task #500 for ItemJoin v4.8-SNAPSHOT generated an exception
java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388) ~[?:?]
	at me.RockinChaos.itemjoin.utils.ProbabilityUtilities.getRandomElement(ProbabilityUtilities.java:51) ~[ItemJoin-4.8-SNAPSHOT.jar:?]
	at me.RockinChaos.itemjoin.listeners.giveitems.SetItems.setProbabilityItems(SetItems.java:67) ~[ItemJoin-4.8-SNAPSHOT.jar:?]
	at me.RockinChaos.itemjoin.listeners.giveitems.PlayerJoin.setJoinItems(PlayerJoin.java:72) ~[ItemJoin-4.8-SNAPSHOT.jar:?]
	at me.RockinChaos.itemjoin.listeners.giveitems.PlayerJoin$2.run(PlayerJoin.java:63) ~[ItemJoin-4.8-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.12.2.jar:git-Paper-1424]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) [patched_1.12.2.jar:git-Paper-1424]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833) [patched_1.12.2.jar:git-Paper-1424]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [patched_1.12.2.jar:git-Paper-1424]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1424]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1424]
	at java.lang.Thread.run(Thread.java:844) [?:?]
```

**Comment by RockinChaos** [comment]
No it's not, they don't throw errors if its missing, it just skips over them as if they aren't defined in the config. Somehow a number is being passed to the Probability counter that it does not like.

Can you post your items.yml pastebin link please?

**Comment by mibby** [comment]
Seems to be fixed, thanks!
