### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by madtomic** [RockinChaos/ItemJoin#181]
[22:49:59 WARN]: Unexpected exception while parsing console command "itemjoin get test madtomic"
org.bukkit.command.CommandException: Unhandled exception executing command 'itemjoin' in plugin ItemJoin v4.8
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[paper-1.12.2.jar:git-Paper-4a4d299]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[paper-1.12.2.jar:git-Paper-4a4d299]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:632) ~[paper-1.12.2.jar:git-Paper-4a4d299]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:595) ~[paper-1.12.2.jar:git-Paper-4a4d299]
        at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:461) ~[paper-1.12.2.jar:git-Paper-4a4d299]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:424) ~[paper-1.12.2.jar:git-Paper-4a4d299]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:773) ~[paper-1.12.2.jar:git-Paper-4a4d299]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) ~[paper-1.12.2.jar:git-Paper-4a4d299]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.ClassCastException: com.destroystokyo.paper.console.TerminalConsoleCommandSender cannot be cast to org.bukkit.entity.Player
        at me.RockinChaos.itemjoin.utils.Language.setArgsPlayer(Language.java:71) ~[?:?]
        at me.RockinChaos.itemjoin.utils.Commands.onCommand(Commands.java:604) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[paper-1.12.2.jar:git-Paper-4a4d299]
        ... 8 more

**Comment by RockinChaos** [comment]
You are using an outdated version of ItemJoin. This is  known issue in v4.8 and has been fixed as of the release of v4.9 (over a month ago) and supports Minecraft version 1.7-1.13.

https://www.spigotmc.org/resources/itemjoin.12661/download?version=233044
