### ISSUE TITLE
Event exception on change world

### ISSUE THREAD

**Issue by SlimeDog** [RockinChaos/ItemJoin#192]
Spigot 1.13.2 latest
ItemJoin 5.0.0-b161
WorldEdit 7.0.0-b3982

On change world:
```
[12:24:49 ERROR]: Could not pass event PlayerMoveEvent to ItemJoin v5.0.0
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:309) ~[spigot-1.13.2.jar-2018-12-25-1937:git-Spigot-82e117e-2b2d084]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.2.jar-2018-12-25-1937:git-Spigot-82e117e-2b2d084]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.2.jar-2018-12-25-1937:git-Spigot-82e117e-2b2d084]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.2.jar-2018-12-25-1937:git-Spigot-82e117e-2b2d084]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:945) ~[spigot-1.13.2.jar-2018-12-25-1937:git-Spigot-82e117e-2b2d084]
        at net.minecraft.server.v1_13_R2.PacketPlayInFlying.a(SourceFile:126) ~[spigot-1.13.2.jar-2018-12-25-1937:git-Spigot-82e117e-2b2d084]
        at net.minecraft.server.v1_13_R2.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) ~[spigot-1.13.2.jar-2018-12-25-1937:git-Spigot-82e117e-2b2d084]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.2.jar-2018-12-25-1937:git-Spigot-82e117e-2b2d084]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar-2018-12-25-1937:git-Spigot-82e117e-2b2d084]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:895) [spigot-1.13.2.jar-2018-12-25-1937:git-Spigot-82e117e-2b2d084]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar-2018-12-25-1937:git-Spigot-82e117e-2b2d084]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:830) [spigot-1.13.2.jar-2018-12-25-1937:git-Spigot-82e117e-2b2d084]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:728) [spigot-1.13.2.jar-2018-12-25-1937:git-Spigot-82e117e-2b2d084]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NoSuchMethodError: com.sk89q.worldguard.internal.platform.WorldGuardPlatform.getWorldByName(Ljava/lang/String;)Lcom/sk89q/worldedit/world/World;
        at me.RockinChaos.itemjoin.giveitems.listeners.RegionEnter.getRegionSets(RegionEnter.java:115) ~[?:?]
        at me.RockinChaos.itemjoin.giveitems.listeners.RegionEnter.isInRegion(RegionEnter.java:105) ~[?:?]
        at me.RockinChaos.itemjoin.giveitems.listeners.RegionEnter.giveOnRegionEnter(RegionEnter.java:36) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot-1.13.2.jar-2018-12-25-1937:git-Spigot-82e117e-2b2d084]
        ... 15 more
```

**Comment by SlimeDog** [comment]
Thanks. It is a bit much.

**Comment by RockinChaos** [comment]
Tested and it seems to be fixed; http://ci.craftationgaming.com/job/ItemJoin/167/

Really wish they would simply deprecate the method and redirect to the new method.
Now in order for me to support multiple versions of Minecraft which includes older versions of WorldGuard I literally have to take their GitHub source and implement the deprecated methods myself which takes several hours to learn work arounds.

**Comment by SlimeDog** [comment]
Yikes!

**Comment by SlimeDog** [comment]
Seems to be fixed in latest IJ releases.
