### ISSUE TITLE
Item Error on respawn

### ISSUE THREAD

**Issue by PrivatePrius** [RockinChaos/ItemJoin#23]
The give-on-modifiers 'respawn' is causing an error.
Updated Spigot just now after 1.9 - /version is up to date
Used the default config as well 

[21:49:46] [Server thread/INFO]: PrivatePrius issued server command: /kill PrivatePrius
[21:49:46] [Server thread/ERROR]: Could not pass event PlayerDeathEvent to ItemJoin v2.6
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-23e921f-8b69bdd]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-23e921f-8b69bdd]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-23e921f-8b69bdd]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-23e921f-8b69bdd]
	at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:399) [spigot.jar:git-Spigot-23e921f-8b69bdd]
	at net.minecraft.server.v1_9_R1.EntityPlayer.die(EntityPlayer.java:421) [spigot.jar:git-Spigot-23e921f-8b69bdd]
	at org.bukkit.craftbukkit.v1_9_R1.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:99) [spigot.jar:git-Spigot-23e921f-8b69bdd]
	at com.earth2me.essentials.commands.Commandkill.updatePlayer(Commandkill.java:41) [EssentialsX-2.0.1.jar:?]
	at com.earth2me.essentials.commands.EssentialsLoopCommand.loopOnlinePlayers(EssentialsLoopCommand.java:98) [EssentialsX-2.0.1.jar:?]
	at com.earth2me.essentials.commands.Commandkill.run(Commandkill.java:23) [EssentialsX-2.0.1.jar:?]
	at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:151) [EssentialsX-2.0.1.jar:?]
	at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:146) [EssentialsX-2.0.1.jar:?]
	at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:456) [EssentialsX-2.0.1.jar:?]
	at com.earth2me.essentials.Essentials.onCommand(Essentials.java:366) [EssentialsX-2.0.1.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot.jar:git-Spigot-23e921f-8b69bdd]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-23e921f-8b69bdd]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) [spigot.jar:git-Spigot-23e921f-8b69bdd]
	at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1350) [spigot.jar:git-Spigot-23e921f-8b69bdd]
	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1185) [spigot.jar:git-Spigot-23e921f-8b69bdd]
	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-23e921f-8b69bdd]
	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-23e921f-8b69bdd]
	at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-23e921f-8b69bdd]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_73]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_73]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-23e921f-8b69bdd]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot.jar:git-Spigot-23e921f-8b69bdd]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-23e921f-8b69bdd]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot.jar:git-Spigot-23e921f-8b69bdd]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot.jar:git-Spigot-23e921f-8b69bdd]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]
Caused by: java.lang.NullPointerException
	at me.RockinChaos.itemjoin.utils.Listeners.isAllowedItem(Listeners.java:578) ~[?:?]
	at me.RockinChaos.itemjoin.utils.Listeners.onDeathDrops(Listeners.java:524) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-23e921f-8b69bdd]
	... 29 more
[21:49:46] [Server thread/INFO]: PrivatePrius died
[21:49:48] [Server thread/INFO]: [ChatEx] There is no new version available. You are up-to-date!
[21:49:48] [Server thread/ERROR]: Could not pass event PlayerRespawnEvent to ItemJoin v2.6
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-23e921f-8b69bdd]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-23e921f-8b69bdd]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-23e921f-8b69bdd]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-23e921f-8b69bdd]
	at net.minecraft.server.v1_9_R1.PlayerList.moveToWorld(PlayerList.java:626) [spigot.jar:git-Spigot-23e921f-8b69bdd]
	at net.minecraft.server.v1_9_R1.PlayerList.moveToWorld(PlayerList.java:555) [spigot.jar:git-Spigot-23e921f-8b69bdd]
	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1606) [spigot.jar:git-Spigot-23e921f-8b69bdd]
	at net.minecraft.server.v1_9_R1.PacketPlayInClientCommand.a(SourceFile:31) [spigot.jar:git-Spigot-23e921f-8b69bdd]
	at net.minecraft.server.v1_9_R1.PacketPlayInClientCommand.a(SourceFile:8) [spigot.jar:git-Spigot-23e921f-8b69bdd]
	at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-23e921f-8b69bdd]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_73]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_73]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-23e921f-8b69bdd]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot.jar:git-Spigot-23e921f-8b69bdd]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-23e921f-8b69bdd]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot.jar:git-Spigot-23e921f-8b69bdd]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot.jar:git-Spigot-23e921f-8b69bdd]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]
Caused by: java.lang.NullPointerException
	at me.RockinChaos.itemjoin.utils.Listeners.onRespawn(Listeners.java:65) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73]

**Comment by RockinChaos** [comment]
Nice trick lol. I will look into this soon. Its going to take some testing since I see some essential bugs in there so I will have to figure out whats going on there. I will get back to you ASAP!

**Comment by RockinChaos** [comment]
Not sure how you obtained this error but it seems to be fixed in ItemJoin v2.7. I have done extensive testing on this and there should be absolutely no errors.

**I plan to release ItemJoin v2.7 tomorrow so look out for it!**

**Comment by PrivatePrius** [comment]
Thank you!
I plan on opening my server tomorrow and am looking forward to this greatly! Thank you for the fast response as well!

**Comment by PrivatePrius** [comment]
How soon are you expecting to release v2.7? I'm very anxious

**Comment by RockinChaos** [comment]
It has been uploaded and waiting for appoval. I am forwarding you that it may be a bit confusing and first to setup. I have completely redone the items.yml structure. Instead of the slot defining the item now a random name can define the item and the slot is defined under that item.

**Comment by PrivatePrius** [comment]
Awesome! Any way I could get a dropbox/drive/mediafire link? :) :) :) :)

**Comment by RockinChaos** [comment]
http://www.spigotmc.org/resources/itemjoin.12661/ uploaded here and already available
