### ISSUE TITLE
 unavailable，help

### ISSUE THREAD

**Issue by mocha666** [RockinChaos/ItemJoin#272]
[17:15:07] [Server thread/ERROR]: [ItemJoin] SQLite exception on initialize
java.sql.SQLException: Error opening connection
	at org.sqlite.core.CoreConnection.open(CoreConnection.java:215) ~[server.jar:git-Spigot-bb614f8-unknown]
	at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76) ~[server.jar:git-Spigot-bb614f8-unknown]
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:25) ~[server.jar:git-Spigot-bb614f8-unknown]
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:24) ~[server.jar:git-Spigot-bb614f8-unknown]
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45) ~[server.jar:git-Spigot-bb614f8-unknown]
	at org.sqlite.JDBC.createConnection(JDBC.java:114) ~[server.jar:git-Spigot-bb614f8-unknown]
	at org.sqlite.JDBC.connect(JDBC.java:88) ~[server.jar:git-Spigot-bb614f8-unknown]
	at java.sql.DriverManager.getConnection(DriverManager.java:664) ~[?:1.8.0_121]
	at java.sql.DriverManager.getConnection(DriverManager.java:270) ~[?:1.8.0_121]
	at me.RockinChaos.itemjoin.utils.sqlite.SQLite.getSQLConnection(SQLite.java:77) [ItemJoin.jar:?]
	at me.RockinChaos.itemjoin.utils.sqlite.Database.executeStatement(Database.java:37) [ItemJoin.jar:?]
	at me.RockinChaos.itemjoin.utils.sqlite.SQLData.createTables(SQLData.java:51) [ItemJoin.jar:?]
	at me.RockinChaos.itemjoin.utils.sqlite.SQLData.<init>(SQLData.java:36) [ItemJoin.jar:?]
	at me.RockinChaos.itemjoin.handlers.ConfigHandler.generateData(ConfigHandler.java:44) [ItemJoin.jar:?]
	at me.RockinChaos.itemjoin.ItemJoin.onEnable(ItemJoin.java:14) [ItemJoin.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [server.jar:git-Spigot-bb614f8-unknown]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [server.jar:git-Spigot-bb614f8-unknown]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [server.jar:git-Spigot-bb614f8-unknown]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:382) [server.jar:git-Spigot-bb614f8-unknown]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:331) [server.jar:git-Spigot-bb614f8-unknown]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [server.jar:git-Spigot-bb614f8-unknown]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [server.jar:git-Spigot-bb614f8-unknown]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [server.jar:git-Spigot-bb614f8-unknown]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [server.jar:git-Spigot-bb614f8-unknown]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [server.jar:git-Spigot-bb614f8-unknown]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.Exception: No native library is found for os.name=Linux and os.arch=x86_64. path=/org/sqlite/native/Linux/x86_64
	at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:333) ~[server.jar:git-Spigot-bb614f8-unknown]
	at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:64) ~[server.jar:git-Spigot-bb614f8-unknown]
	at org.sqlite.core.NativeDB.load(NativeDB.java:56) ~[server.jar:git-Spigot-bb614f8-unknown]
	at org.sqlite.core.CoreConnection.open(CoreConnection.java:211) ~[server.jar:git-Spigot-bb614f8-unknown]
	... 25 more
[17:15:07] [Server thread/ERROR]: Error occurred while enabling ItemJoin v5.0.5-RELEASE-b324 (Is it up to date?)
java.lang.NullPointerException: null
	at me.RockinChaos.itemjoin.utils.sqlite.Database.executeStatement(Database.java:38) ~[?:?]
	at me.RockinChaos.itemjoin.utils.sqlite.SQLData.createTables(SQLData.java:51) ~[?:?]
	at me.RockinChaos.itemjoin.utils.sqlite.SQLData.<init>(SQLData.java:36) ~[?:?]
	at me.RockinChaos.itemjoin.handlers.ConfigHandler.generateData(ConfigHandler.java:44) ~[?:?]
	at me.RockinChaos.itemjoin.ItemJoin.onEnable(ItemJoin.java:14) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[server.jar:git-Spigot-bb614f8-unknown]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [server.jar:git-Spigot-bb614f8-unknown]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [server.jar:git-Spigot-bb614f8-unknown]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:382) [server.jar:git-Spigot-bb614f8-unknown]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:331) [server.jar:git-Spigot-bb614f8-unknown]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [server.jar:git-Spigot-bb614f8-unknown]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [server.jar:git-Spigot-bb614f8-unknown]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [server.jar:git-Spigot-bb614f8-unknown]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [server.jar:git-Spigot-bb614f8-unknown]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [server.jar:git-Spigot-bb614f8-unknown]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

**Comment by RockinChaos** [comment]
Can you please try the latest version of ItemJoin as I have fixed bugs relating to the database.
Link; https://www.spigotmc.org/resources/itemjoin.12661/download?version=320427
Recent Changes; https://github.com/RockinChaos/ItemJoin/wiki/Recent-Changes
