### ISSUE TITLE
NPE on use IJ item

### ISSUE THREAD

**Issue by SlimeDog** [RockinChaos/ItemJoin#296]
## Thanks for taking the time to open a bug report!

**Describe the bug**
I see this error whenever I use an IJ item (I have only one). No changes to config.yml or items.yml. Have I missed a configuration change?

**To Reproduce**
1. Update to ItemJoin 5.0.7-SNAPSHOT-b424
2. Start server
3. Click IJ item

**Pastebin**
Relevant IJ item (unchanged):
```
items:
  changeWorld-tool:
    id: CLOCK
    slot: 8
    count: 1
    name: '&bNavigate'
    lore:
      - 'Teleport elsewhere'
    commands:
      right-click:
        - 'deluxemenus open navigation'
    itemflags: cancel-events, death-drops, hide-attributes, hide-durability, inventory-modify, placement, self-drops, unbreakable
    triggers: join, respawn, world-change
    permission-node: 'deluxemenus.open'
    # disabled-worlds-UNSUPPORTED: world_void
    enabled-worlds: world, world_lobby, world_blackdog, world_city, world_luckyblock, world_minigames, world_skyblock, world_westeros, world_whitedog, world_yellowdog
```

**Please complete the following information:**
 - Resource Version and Build Number: 5.0.7-SNAPSHOT-b424
 - Server Version: 1.15.2 (Jenkins 2692)

```
[08:45:32] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to ItemJoin v5.0.7-SNAPSHOT-b424
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.15.2.jar-2020-06-06-0530:git-Spigot-a99063f-fad2494]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.15.2.jar-2020-06-06-0530:git-Spigot-a99063f-fad2494]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.15.2.jar-2020-06-06-0530:git-Spigot-a99063f-fad2494]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.15.2.jar-2020-06-06-0530:git-Spigot-a99063f-fad2494]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:450) ~[spigot-1.15.2.jar-2020-06-06-0530:git-Spigot-a99063f-fad2494]
        at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:441) ~[spigot-1.15.2.jar-2020-06-06-0530:git-Spigot-a99063f-fad2494]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1251) ~[?:git-Spigot-a99063f-fad2494]
        at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[spigot-1.15.2.jar-2020-06-06-0530:git-Spigot-a99063f-fad2494]
        at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot-1.15.2.jar-2020-06-06-0530:git-Spigot-a99063f-fad2494]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.15.2.jar-2020-06-06-0530:git-Spigot-a99063f-fad2494]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [spigot-1.15.2.jar-2020-06-06-0530:git-Spigot-a99063f-fad2494]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.15.2.jar-2020-06-06-0530:git-Spigot-a99063f-fad2494]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.15.2.jar-2020-06-06-0530:git-Spigot-a99063f-fad2494]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.15.2.jar-2020-06-06-0530:git-Spigot-a99063f-fad2494]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918) [spigot-1.15.2.jar-2020-06-06-0530:git-Spigot-a99063f-fad2494]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911) [spigot-1.15.2.jar-2020-06-06-0530:git-Spigot-a99063f-fad2494]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(SourceFile:103) [spigot-1.15.2.jar-2020-06-06-0530:git-Spigot-a99063f-fad2494]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:894) [spigot-1.15.2.jar-2020-06-06-0530:git-Spigot-a99063f-fad2494]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828) [spigot-1.15.2.jar-2020-06-06-0530:git-Spigot-a99063f-fad2494]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
        at me.RockinChaos.itemjoin.listeners.Interact.onInteractCancel(Interact.java:58) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.15.2.jar-2020-06-06-0530:git-Spigot-a99063f-fad2494]
        ... 19 more
```

**Comment by RockinChaos** [comment]
Thanks for letting me know about this, looks like it had to do with the changes I did for canceling book and quill interactions.

It should be resolved in the latest snapshot: http://ci.craftationgaming.com/job/ItemJoin/426/

Let me know if this issue continues.

**Comment by SlimeDog** [comment]
Confirmed fixed in b426. Thanks.
