### ISSUE TITLE
Itemjoin 2.9 Errors On Join & Reload

### ISSUE THREAD

**Issue by TNZGriff** [RockinChaos/ItemJoin#32]
Hello! I am using a fresh install of Itemjoin 2.9, haven't changed any configs or files, and I am receiving the following errors when I join the game:

```
[23:10:40] [Server thread/ERROR]: **** THIS IS NOT AN ISSUE TO DO WITH PER WORLD PLUGINS ****
Could not pass event PlayerJoinEvent to ItemJoin v2.9
org.bukkit.event.EventException
    at me.incomprehendable.dev.pwp.transparentlisteners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:118) ~[?:?]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-5a40365-b103841]
    at me.incomprehendable.dev.pwp.transparentlisteners.PWPRegisteredListener.callEvent(PWPRegisteredListener.java:28) [PerWorldPlugins.jar:?]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-5a40365-b103841]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-5a40365-b103841]
    at net.minecraft.server.v1_9_R1.PlayerList.onPlayerJoin(PlayerList.java:332) [spigot.jar:git-Spigot-5a40365-b103841]
    at net.minecraft.server.v1_9_R1.PlayerList.a(PlayerList.java:158) [spigot.jar:git-Spigot-5a40365-b103841]
    at net.minecraft.server.v1_9_R1.LoginListener.b(LoginListener.java:144) [spigot.jar:git-Spigot-5a40365-b103841]
    at net.minecraft.server.v1_9_R1.LoginListener.c(LoginListener.java:54) [spigot.jar:git-Spigot-5a40365-b103841]
    at net.minecraft.server.v1_9_R1.NetworkManager.a(NetworkManager.java:232) [spigot.jar:git-Spigot-5a40365-b103841]
    at net.minecraft.server.v1_9_R1.ServerConnection.c(ServerConnection.java:141) [spigot.jar:git-Spigot-5a40365-b103841]
    at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:820) [spigot.jar:git-Spigot-5a40365-b103841]
    at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-5a40365-b103841]
    at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot.jar:git-Spigot-5a40365-b103841]
    at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot.jar:git-Spigot-5a40365-b103841]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_05]
Caused by: java.lang.NullPointerException
    at me.RockinChaos.itemjoin.ItemJoin.CacheItems(ItemJoin.java:199) ~[?:?]
    at me.RockinChaos.itemjoin.Listeners.JoinItem.JoinItem.giveOnJoin(JoinItem.java:45) ~[?:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_05]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_05]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_05]
    at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_05]
    at me.incomprehendable.dev.pwp.transparentlisteners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:116) ~[?:?]
    ... 15 more
```

Even though it blatantly said that it had nothing to do with PWP, I uninstalled PWP anyway and then started getting this error:

```
[23:24:55] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to ItemJoin v2.9
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-5a40365-b103841]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-5a40365-b103841]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-5a40365-b103841]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-5a40365-b103841]
    at net.minecraft.server.v1_9_R1.PlayerList.onPlayerJoin(PlayerList.java:332) [spigot.jar:git-Spigot-5a40365-b103841]
    at net.minecraft.server.v1_9_R1.PlayerList.a(PlayerList.java:158) [spigot.jar:git-Spigot-5a40365-b103841]
    at net.minecraft.server.v1_9_R1.LoginListener.b(LoginListener.java:144) [spigot.jar:git-Spigot-5a40365-b103841]
    at net.minecraft.server.v1_9_R1.LoginListener.c(LoginListener.java:54) [spigot.jar:git-Spigot-5a40365-b103841]
    at net.minecraft.server.v1_9_R1.NetworkManager.a(NetworkManager.java:232) [spigot.jar:git-Spigot-5a40365-b103841]
    at net.minecraft.server.v1_9_R1.ServerConnection.c(ServerConnection.java:141) [spigot.jar:git-Spigot-5a40365-b103841]
    at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:820) [spigot.jar:git-Spigot-5a40365-b103841]
    at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-5a40365-b103841]
    at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot.jar:git-Spigot-5a40365-b103841]
    at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot.jar:git-Spigot-5a40365-b103841]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_05]
Caused by: java.lang.NullPointerException
    at me.RockinChaos.itemjoin.ItemJoin.CacheItems(ItemJoin.java:199) ~[?:?]
    at me.RockinChaos.itemjoin.Listeners.JoinItem.JoinItem.giveOnJoin(JoinItem.java:45) ~[?:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_05]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_05]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_05]
    at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_05]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-5a40365-b103841]
    ... 14 more
```

I get similar errors when I change worlds. I also get 'An internal error occurred while attempting to perform this command' as well as the following error when I use /itemjoin reload:

```
[23:26:04] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'itemjoin' in plugin ItemJoin v2.9
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-5a40365-b103841]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-5a40365-b103841]
    at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigot.jar:git-Spigot-5a40365-b103841]
    at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1350) [spigot.jar:git-Spigot-5a40365-b103841]
    at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1185) [spigot.jar:git-Spigot-5a40365-b103841]
    at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-5a40365-b103841]
    at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-5a40365-b103841]
    at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-5a40365-b103841]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_05]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_05]
    at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-5a40365-b103841]
    at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot.jar:git-Spigot-5a40365-b103841]
    at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-5a40365-b103841]
    at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot.jar:git-Spigot-5a40365-b103841]
    at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot.jar:git-Spigot-5a40365-b103841]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_05]
Caused by: java.lang.NullPointerException
    at me.RockinChaos.itemjoin.ItemJoin.CacheItems(ItemJoin.java:199) ~[?:?]
    at me.RockinChaos.itemjoin.utils.Commands.onCommand(Commands.java:108) ~[?:?]
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-5a40365-b103841]
    ... 15 more
```

These issues do not persist on version 2.8, and I get items on 2.8, which I do not on 2.9, but the biggest reason I am using this plugin is for the ability to use custom books. With the 2.8 version, the books show up, but they just say '* Invalid book tag *' which is to be expected. Is there some way that I can solve the issues I am having with version 2.9, or will I simply have to wait for an update? Once again, these errors are coming from a clean install of Itemjoin 2.9.

**Comment by RockinChaos** [comment]
What version of spigot are you using? If it's 1.9 are you up to date? Check with /version

**Comment by TNZGriff** [comment]
Wow, I made this jar with Buildtools only a couple of days ago and apparently it was 9 versions behind. It seems to be working now, thanks!
