### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by SlimeDog** [RockinChaos/ItemJoin#324]
## Thanks for taking the time to open a bug report!

**Describe the bug**
```
[14:49:44] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to ItemJoin v5.0.7-SNAPSHOT-b504
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.16.2.jar-2020-08-13-1751:git-Spigot-379750e-1e76d09]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.16.2.jar-2020-08-13-1751:git-Spigot-379750e-1e76d09]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.16.2.jar-2020-08-13-1751:git-Spigot-379750e-1e76d09]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.16.2.jar-2020-08-13-1751:git-Spigot-379750e-1e76d09]
        at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:478) ~[spigot-1.16.2.jar-2020-08-13-1751:git-Spigot-379750e-1e76d09]
        at net.minecraft.server.v1_16_R2.PlayerInteractManager.a(PlayerInteractManager.java:444) ~[spigot-1.16.2.jar-2020-08-13-1751:git-Spigot-379750e-1e76d09]
        at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1278) ~[spigot-1.16.2.jar-2020-08-13-1751:git-Spigot-379750e-1e76d09]
        at net.minecraft.server.v1_16_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[spigot-1.16.2.jar-2020-08-13-1751:git-Spigot-379750e-1e76d09]
        at net.minecraft.server.v1_16_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot-1.16.2.jar-2020-08-13-1751:git-Spigot-379750e-1e76d09]
        at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.16.2.jar-2020-08-13-1751:git-Spigot-379750e-1e76d09]
        at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[spigot-1.16.2.jar-2020-08-13-1751:git-Spigot-379750e-1e76d09]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot-1.16.2.jar-2020-08-13-1751:git-Spigot-379750e-1e76d09]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.16.2.jar-2020-08-13-1751:git-Spigot-379750e-1e76d09]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot-1.16.2.jar-2020-08-13-1751:git-Spigot-379750e-1e76d09]
        at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:941) ~[spigot-1.16.2.jar-2020-08-13-1751:git-Spigot-379750e-1e76d09]
        at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:934) ~[spigot-1.16.2.jar-2020-08-13-1751:git-Spigot-379750e-1e76d09]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeAll(SourceFile:103) ~[spigot-1.16.2.jar-2020-08-13-1751:git-Spigot-379750e-1e76d09]
        at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:917) ~[spigot-1.16.2.jar-2020-08-13-1751:git-Spigot-379750e-1e76d09]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:850) ~[spigot-1.16.2.jar-2020-08-13-1751:git-Spigot-379750e-1e76d09]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.2.jar-2020-08-13-1751:git-Spigot-379750e-1e76d09]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
        at me.RockinChaos.itemjoin.listeners.Commands.onInteract(Commands.java:191) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.16.2.jar-2020-08-13-1751:git-Spigot-379750e-1e76d09]
        ... 20 more
```

**To Reproduce**
1. Kill a spider?

**Please complete the following information:**
```
>version
[14:54:15] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-379750e-1e76d09 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)
[14:54:15] [Server thread/INFO]: You are running the latest version
>version ItemJoin
[14:54:18] [Server thread/INFO]: ItemJoin version 5.0.7-SNAPSHOT-b504
[14:54:18] [Server thread/INFO]: Get custom items on join.
[14:54:18] [Server thread/INFO]: Website: https://www.spigotmc.org/resources/itemjoin.12661/
[14:54:18] [Server thread/INFO]: Author: RockinChaos
```

**Comment by RockinChaos** [comment]
Sorry about that, should be resolved now; http://ci.craftationgaming.com/job/ItemJoin/506/

**Comment by SlimeDog** [comment]
That seems to have done the needful. Thanks.
