### ISSUE TITLE
Database error on startup

### ISSUE THREAD

**Issue by SlimeDog** [RockinChaos/ItemJoin#332]
## Thanks for taking the time to open a bug report!

Spigot 1.16.3
ItemJoin 5.1.1-SNAPSHOT-b549

**Describe the bug**
Database error on startup.

**To Reproduce**
1. Install ItemJoin 5.1.1-SNAPSHOT-b549
2. Start server
3. See error in log

**Expected behavior**
Clean database update.

**Log**
```
[21:20:26] [Craft Scheduler Thread - 17/ERROR]: [ItemJoin_ERROR] {SQLite} [1] Failed to execute database statement.
[21:20:26] [Craft Scheduler Thread - 17/ERROR]: [ItemJoin_ERROR] {SQLite} [1] Database Status: Open: true! Writable: true!
[21:20:26] [Craft Scheduler Thread - 17/ERROR]: [ItemJoin_ERROR] {SQLite} [1] Statement: ALTER TABLE return_items RENAME TO ij_return_items;
[21:20:26] [Craft Scheduler Thread - 17/WARN]: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (there is already another table or index with this name: ij_return_items)
[21:20:26] [Craft Scheduler Thread - 17/WARN]:  at org.sqlite.core.DB.newSQLException(DB.java:1010)
[21:20:26] [Craft Scheduler Thread - 17/WARN]:  at org.sqlite.core.DB.newSQLException(DB.java:1022)
[21:20:26] [Craft Scheduler Thread - 17/WARN]:  at org.sqlite.core.DB.throwex(DB.java:987)
[21:20:26] [Craft Scheduler Thread - 17/WARN]:  at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
[21:20:26] [Craft Scheduler Thread - 17/WARN]:  at org.sqlite.core.NativeDB.prepare(NativeDB.java:134)
[21:20:26] [Craft Scheduler Thread - 17/WARN]:  at org.sqlite.core.DB.prepare(DB.java:264)
[21:20:26] [Craft Scheduler Thread - 17/WARN]:  at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:45)
[21:20:26] [Craft Scheduler Thread - 17/WARN]:  at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30)
[21:20:26] [Craft Scheduler Thread - 17/WARN]:  at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:19)
[21:20:26] [Craft Scheduler Thread - 17/WARN]:  at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:35)
[21:20:26] [Craft Scheduler Thread - 17/WARN]:  at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:241)
[21:20:26] [Craft Scheduler Thread - 17/WARN]:  at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205)
[21:20:26] [Craft Scheduler Thread - 17/WARN]:  at me.RockinChaos.itemjoin.utils.sqlite.Database.executeStatement(Database.java:67)
[21:20:26] [Craft Scheduler Thread - 17/WARN]:  at me.RockinChaos.itemjoin.utils.sqlite.SQLite.alterTables(SQLite.java:125)
[21:20:26] [Craft Scheduler Thread - 17/WARN]:  at me.RockinChaos.itemjoin.utils.sqlite.SQLite.createTables(SQLite.java:92)
[21:20:26] [Craft Scheduler Thread - 17/WARN]:  at me.RockinChaos.itemjoin.utils.sqlite.SQLite.lambda$new$0(SQLite.java:71)
[21:20:26] [Craft Scheduler Thread - 17/WARN]:  at me.RockinChaos.itemjoin.handlers.ServerHandler.lambda$runAsyncThread$0(ServerHandler.java:43)
[21:20:26] [Craft Scheduler Thread - 17/WARN]:  at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:81)
[21:20:26] [Craft Scheduler Thread - 17/WARN]:  at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[21:20:26] [Craft Scheduler Thread - 17/WARN]:  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[21:20:26] [Craft Scheduler Thread - 17/WARN]:  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[21:20:26] [Craft Scheduler Thread - 17/WARN]:  at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by RockinChaos** [comment]
Sorry about that, looks like it was a typo.
Should now be fixed in the latest snapshot: http://ci.craftationgaming.com/job/ItemJoin/550/

Let me know!

**Comment by SlimeDog** [comment]
Confirmed fixed in build 550.
