### ISSUE TITLE
Error when joining while whitelist on

### ISSUE THREAD

**Issue by crimilo** [RockinChaos/ItemJoin#336]
## Thanks for taking the time to open a bug report!

**Describe the bug**

[11:03:54 INFO]: UUID of player Kyqq is ec140c45-c18c-4efe-a825-5fbe6eea8184
[11:03:54 INFO]: Disconnecting com.mojang.authlib.GameProfile@50891246[id=ec140c45-c18c-4efe-a825-5fbe6eea8184,name=Kyqq,properties={textures=[com.mojang.authlib.properties.Property@5ee51e2]},legacy=false] (/62.98.61.132:50735): Non sei whitelistato su questo server!
[11:03:54 ERROR]: Could not pass event PlayerLoginEvent to ItemJoin v5.1.0-RELEASE-b545
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PlayerList.attemptLogin(PlayerList.java:472) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:118) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:875) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
Caused by: java.util.NoSuchElementException: packet_handler
        at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:907) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:157) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:150) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at me.RockinChaos.itemjoin.utils.protocol.TinyProtocol.injectChannelInternal(TinyProtocol.java:368) ~[?:?]
        at me.RockinChaos.itemjoin.utils.protocol.TinyProtocol.injectPlayer(TinyProtocol.java:344) ~[?:?]
        at me.RockinChaos.itemjoin.utils.protocol.TinyProtocol$4.onPlayerLogin(TinyProtocol.java:168) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        ... 14 more

**To Reproduce**
1. Go to '...' See title

**Expected behavior**

**Screenshots**

**Pastebin**
Even if it is not related to the problem, please include ALL configuration files in separate Pastebin.com links as well as any related error codes from the console window.

**Please complete the following information:**
 - Resource Version and Build Number: [e.g. 5.0.6-b364]
 - Server Version [e.g. Spigot-1.15.2]

**Additional context**

**Comment by RockinChaos** [comment]
I am 99% sure this is already fixed in the latest snapshot, please try it and let me know!
Link: https://ci.craftationgaming.com/job/ItemJoin/570/

**Comment by crimilo** [comment]
Looks like its fixed, thanks
