### ISSUE TITLE
[Bug] Using command "/ij get <item> <player>" in console

### ISSUE THREAD

**Issue by momoservertw** [RockinChaos/ItemJoin#342]
**Describe the bug**
Can not using command "/ij get <item> <player>" in console.
I tried some items, and they both showed this error.
```
[16:41:17 WARN]: Unexpected exception while parsing console command "ij get GP1 AllBye"
org.bukkit.command.CommandException: Unhandled exception executing command 'ij' in plugin ItemJoin v5.1.0-RELEASE-b545
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.4.jar:git-Paper-261]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.4.jar:git-Paper-261]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:802) ~[patched_1.16.4.jar:git-Paper-261]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:764) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:411) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:378) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1211) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-261]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]
Caused by: java.lang.ClassCastException: com.destroystokyo.paper.console.TerminalConsoleCommandSender cannot be cast to org.bukkit.entity.Player
        at me.RockinChaos.itemjoin.ChatExecutor.handleItems(ChatExecutor.java:446) ~[?:?]
        at me.RockinChaos.itemjoin.ChatExecutor.onCommand(ChatExecutor.java:194) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.4.jar:git-Paper-261]
        ... 9 more
```

**To Reproduce**
1. Console input "ij get <item> <player>"

**Pastebin**
Error message:
https://pastebin.com/HkippXq0

config.yml
https://pastebin.com/7JaxWKfZ

items.yml
https://pastebin.com/T2Rmv1nC

**Please complete the following information:**
- ItemJoin version: v5.1.0-RELEASE-b545
- Paper version: git-Paper-261 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

**Comment by RockinChaos** [comment]
Already resolved in the latest snapshot; https://ci.craftationgaming.com/job/ItemJoin/573/

**Comment by momoservertw** [comment]
The latest build doesn't have this problem.
Thanks~~
