### ISSUE TITLE
Is there an error everytime a player join

### ISSUE THREAD

**Issue by GoT-HiM** [RockinChaos/ItemJoin#344]
Actual Error: 
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125) ~[patched_1.12.2.jar:git-Paper-1618]
	at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:249) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[patched_1.12.2.jar:git-Paper-1618]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[patched_1.12.2.jar:git-Paper-1618]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[patched_1.12.2.jar:git-Paper-1618]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[patched_1.12.2.jar:git-Paper-1618]
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106) ~[patched_1.12.2.jar:git-Paper-1618]
	at me.RockinChaos.itemjoin.utils.protocol.TinyProtocol$PacketInterceptor.write(TinyProtocol.java:505) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[patched_1.12.2.jar:git-Paper-1618]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[patched_1.12.2.jar:git-Paper-1618]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[patched_1.12.2.jar:git-Paper-1618]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[patched_1.12.2.jar:git-Paper-1618]
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106) ~[patched_1.12.2.jar:git-Paper-1618]
	at LPX.ac.write(Unknown Source) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[patched_1.12.2.jar:git-Paper-1618]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[patched_1.12.2.jar:git-Paper-1618]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[patched_1.12.2.jar:git-Paper-1618]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[patched_1.12.2.jar:git-Paper-1618]
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106) ~[patched_1.12.2.jar:git-Paper-1618]
	at me.neznamy.tab.platforms.bukkit.Injector$1.write(Injector.java:75) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[patched_1.12.2.jar:git-Paper-1618]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[patched_1.12.2.jar:git-Paper-1618]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[patched_1.12.2.jar:git-Paper-1618]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[patched_1.12.2.jar:git-Paper-1618]
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106) ~[patched_1.12.2.jar:git-Paper-1618]
	at kernitus.plugin.OldCombatMechanics.utilities.packet.PacketInjector.write(PacketInjector.java:176) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[patched_1.12.2.jar:git-Paper-1618]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[patched_1.12.2.jar:git-Paper-1618]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[patched_1.12.2.jar:git-Paper-1618]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[patched_1.12.2.jar:git-Paper-1618]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111) ~[patched_1.12.2.jar:git-Paper-1618]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[patched_1.12.2.jar:git-Paper-1618]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[patched_1.12.2.jar:git-Paper-1618]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[patched_1.12.2.jar:git-Paper-1618]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[patched_1.12.2.jar:git-Paper-1618]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[patched_1.12.2.jar:git-Paper-1618]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071) ~[patched_1.12.2.jar:git-Paper-1618]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300) ~[patched_1.12.2.jar:git-Paper-1618]
	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327) ~[?:?]
	at net.minecraft.server.v1_12_R1.NetworkManager$4.run(NetworkManager.java:215) ~[patched_1.12.2.jar:git-Paper-1618]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:321) ~[?:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[patched_1.12.2.jar:git-Paper-1618]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) ~[patched_1.12.2.jar:git-Paper-1618]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:309) ~[patched_1.12.2.jar:git-Paper-1618]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[patched_1.12.2.jar:git-Paper-1618]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272]

**Comment by RockinChaos** [comment]
I am pretty sure this is already fixed in the latest snapshot; https://ci.craftationgaming.com/job/ItemJoin/579/

Also in the future please try to use pastebin.com to post console errors.

Let me know!
