### ISSUE TITLE
ClassCastException on plugin enable

### ISSUE THREAD

**Issue by SlimeDog** [RockinChaos/ItemJoin#349]
## Thanks for taking the time to open a bug report!

**Describe the bug**
ClassCastException on plugin enable

No issue with b582 or previous.

**To Reproduce**
1. Update to ItemJoin 5.1.1-SNAPSHOT-b583
2. Start server
3. Observe ERROR in log

**Log ERROR**
```
[21:52:21] [Server thread/INFO]: [ItemJoin] Enabling ItemJoin v5.1.1-SNAPSHOT-b583
[21:52:21] [Server thread/ERROR]: Error occurred while enabling ItemJoin v5.1.1-SNAPSHOT-b583 (Is it up to date?)
java.lang.ClassCastException: class org.sqlite.jdbc4.JDBC4ResultSet cannot be cast to class java.sql.Connection (org.sqlite.jdbc4.JDBC4ResultSet is in unnamed module of loader 'app'; java.sql.Connection is in module java.sql of loader 'platform')
        at me.RockinChaos.itemjoin.utils.sqlite.Controller.isClosed(Database.java:480) ~[?:?]
        at me.RockinChaos.itemjoin.utils.sqlite.Controller.close(Database.java:506) ~[?:?]
        at me.RockinChaos.itemjoin.utils.sqlite.Database.tableExists(Database.java:334) ~[?:?]
        at me.RockinChaos.itemjoin.utils.sqlite.SQL.alterTables(SQL.java:805) ~[?:?]
        at me.RockinChaos.itemjoin.utils.sqlite.SQL.createTables(SQL.java:787) ~[?:?]
        at me.RockinChaos.itemjoin.utils.sqlite.SQL.<init>(SQL.java:68) ~[?:?]
        at me.RockinChaos.itemjoin.utils.sqlite.SQL.getData(SQL.java:948) ~[?:?]
        at me.RockinChaos.itemjoin.handlers.ConfigHandler.registerClasses(ConfigHandler.java:126) ~[?:?]
        at me.RockinChaos.itemjoin.handlers.ConfigHandler.getConfig(ConfigHandler.java:570) ~[?:?]
        at me.RockinChaos.itemjoin.ItemJoin.onEnable(ItemJoin.java:53) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.16.4.jar-2020-11-25-1559:git-Spigot-a19903d-e1ebdd9]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[spigot-1.16.4.jar-2020-11-25-1559:git-Spigot-a19903d-e1ebdd9]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.16.4.jar-2020-11-25-1559:git-Spigot-a19903d-e1ebdd9]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:494) ~[spigot-1.16.4.jar-2020-11-25-1559:git-Spigot-a19903d-e1ebdd9]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:408) ~[spigot-1.16.4.jar-2020-11-25-1559:git-Spigot-a19903d-e1ebdd9]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:435) ~[spigot-1.16.4.jar-2020-11-25-1559:git-Spigot-a19903d-e1ebdd9]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:218) ~[spigot-1.16.4.jar-2020-11-25-1559:git-Spigot-a19903d-e1ebdd9]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:809) ~[spigot-1.16.4.jar-2020-11-25-1559:git-Spigot-a19903d-e1ebdd9]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.4.jar-2020-11-25-1559:git-Spigot-a19903d-e1ebdd9]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Please complete the following information:**
 - ItemJoin 5.1.1-SNAPSHOT-b583
 - Spigot 1.16.4

**Comment by RockinChaos** [comment]
I only cry in URL links; https://ci.craftationgaming.com/job/ItemJoin/584/

**Comment by SlimeDog** [comment]
All better now, with b584. Thanks.
