### ISSUE TITLE
Not giving/dropping items

### ISSUE THREAD

**Issue by kalebbroo** [RockinChaos/ItemJoin#357]
## Thanks for taking the time to open an assistance request!

**Please describe your question or what you need help with, in the best detain you can.**

I just started using Itemjoin I created a custom item and had it drop from Salmon at 1.0 (100%). The item does not drop and an exception is generated on the console. 

"[20:32:23 WARN]: [ItemJoin] Plugin ItemJoin v5.1.1-SNAPSHOT-b658 generated an exception while executing task 31492
java.lang.IllegalStateException: Asynchronous entity add!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.16.5.jar:git-Paper-436]
        at net.minecraft.server.v1_16_R3.WorldServer.addEntity0(WorldServer.java:1151) ~[patched_1.16.5.jar:git-Paper-436]
        at net.minecraft.server.v1_16_R3.WorldServer.addEntity(WorldServer.java:1088) ~[patched_1.16.5.jar:git-Paper-436]
        at org.bukkit.craftbukkit.v1_16_R3.CraftWorld.dropItem(CraftWorld.java:750) ~[patched_1.16.5.jar:git-Paper-436]
        at me.RockinChaos.itemjoin.listeners.Entities.lambda$onMobDeath$0(Entities.java:49) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.5.jar:git-Paper-436]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-436]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-436]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]"

**Pastebin**
Items.yml https://pastebin.com/a10DrsUZ
config.yml https://pastebin.com/fb2Db6j0

**Please complete the following information:**
 Resource Version and Build Number: 5.1.1-SNAPSHOT-b658
 Server Version Paper 1.16.5

**Additional context**
I am able to add items and use the give command to use the items. No issues when I do that.

**Comment by RockinChaos** [comment]
This bug has been officially fixed in the release of ItemJoin v5.2.0.
You can grab it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=383801

Please read the changelog as the documentation has not been updated yet;
https://github.com/RockinChaos/ItemJoin/wiki/Recent-Changes
