### ISSUE TITLE
Connection leak detection triggered

### ISSUE THREAD

**Issue by mibby** [RockinChaos/ItemJoin#369]
- ItemJoin dev 674
 - Paper dev 460 (Spigot 1.16.5)

Noticed this error after someone made a lag machine on my server. Banning the users / removing the lag machine, no more error. I assume it just lost connection because of low TPS.

```
[09:31:35] [Craft Scheduler Thread - 1151 - ItemJoin/INFO]: [com.zaxxer.hikari.HikariDataSource] HikariPool-1 - Starting...
[09:31:35] [Craft Scheduler Thread - 1151 - ItemJoin/INFO]: [com.zaxxer.hikari.HikariDataSource] HikariPool-1 - Start completed.
[09:31:35] [Craft Scheduler Thread - 1122 - ItemJoin/INFO]: [com.zaxxer.hikari.HikariDataSource] HikariPool-1 - Starting...
[09:31:35] [Craft Scheduler Thread - 1122 - ItemJoin/INFO]: [com.zaxxer.hikari.HikariDataSource] HikariPool-1 - Start completed.
[09:31:35] [Craft Scheduler Thread - 1174 - ItemJoin/INFO]: [com.zaxxer.hikari.HikariDataSource] HikariPool-1 - Starting...
[09:31:35] [Craft Scheduler Thread - 1174 - ItemJoin/INFO]: [com.zaxxer.hikari.HikariDataSource] HikariPool-1 - Start completed.
[09:31:35] [Craft Scheduler Thread - 1169 - ItemJoin/INFO]: [com.zaxxer.hikari.HikariDataSource] HikariPool-1 - Starting...
[09:31:35] [Craft Scheduler Thread - 1169 - ItemJoin/INFO]: [com.zaxxer.hikari.HikariDataSource] HikariPool-1 - Start completed.
[09:31:40] [Server thread/INFO]: [com.zaxxer.hikari.HikariDataSource] HikariPool-1 - Shutdown initiated...
[09:31:40] [Server thread/INFO]: [com.zaxxer.hikari.HikariDataSource] HikariPool-1 - Shutdown completed.
[09:32:35] [HikariPool-1 housekeeper/WARN]: [com.zaxxer.hikari.pool.ProxyLeakTask] Connection leak detection triggered for org.sqlite.jdbc4.JDBC4Connection@622de664 on thread Craft Scheduler Thread - 1122 - ItemJoin, stack trace follows
java.lang.Exception: Apparent connection leak detected
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100) ~[?:?]
	at me.RockinChaos.itemjoin.utils.sql.Controller.getConnection(Database.java:458) ~[?:?]
	at me.RockinChaos.itemjoin.utils.sql.Database.executeStatement(Database.java:66) ~[?:?]
	at me.RockinChaos.itemjoin.utils.sql.SQL.lambda$executeLaterStatements$0(SQL.java:57) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[1.16.5-patched.jar: ]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58) ~[1.16.5-patched.jar: ]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[1.16.5-patched.jar: ]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
[09:32:35] [HikariPool-1 housekeeper/WARN]: [com.zaxxer.hikari.pool.ProxyLeakTask] Connection leak detection triggered for org.sqlite.jdbc4.JDBC4Connection@40faf6f6 on thread Craft Scheduler Thread - 1174 - ItemJoin, stack trace follows
java.lang.Exception: Apparent connection leak detected
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100) ~[?:?]
	at me.RockinChaos.itemjoin.utils.sql.Controller.getConnection(Database.java:458) ~[?:?]
	at me.RockinChaos.itemjoin.utils.sql.Database.executeStatement(Database.java:66) ~[?:?]
	at me.RockinChaos.itemjoin.utils.sql.SQL.lambda$executeLaterStatements$0(SQL.java:57) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[1.16.5-patched.jar: ]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58) ~[1.16.5-patched.jar: ]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[1.16.5-patched.jar: ]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Comment by RockinChaos** [comment]
This would indeed occur due to low TPS, ill still look into this anyways just-in-case. 
It's a good thing to see this error though as it force kills the SQL connection to prevent a server crash, restoring the connection once things are stable.

**Comment by RockinChaos** [comment]
Turns out there were some MAJOR bugs with the database not even functioning so it's entirely possible that this error was dramatized due to the lag machines which made it visible.

Either way, the latest snapshot should resolve these issues, also THANK YOU for posting this as I would have never noticed the database bugs. Literally, none of the functions were working in the release build v5.2.0 that was published 8 hours ago. So this is a very needed quick fix.

Link; https://ci.craftationgaming.com/job/ItemJoin/677/
**Remember to remove your old ItemJoin.jar file**

**Comment by mibby** [comment]
Thanks for the quick fix! Glad to have helped.

**Comment by RockinChaos** [comment]
Officially fixed in the latest release,

You can now download it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=384212
