### ISSUE TITLE
ERROR, HELP!

### ISSUE THREAD

**Issue by yurabens** [RockinChaos/ItemJoin#371]
There was an error in the console, help to solve the problem

`[04:11:27 ERROR]: Could not pass event PlayerChangedWorldEvent to ItemJoin v5.2.1-RELEASE-b678
java.lang.NullPointerException: null
 at me.RockinChaos.itemjoin.item.ItemUtilities.pasteReturnItems(ItemUtilities.java:538) ~[?:?]
 at me.RockinChaos.itemjoin.item.ItemUtilities.safeSet(ItemUtilities.java:258) ~[?:?]
 at me.RockinChaos.itemjoin.item.ItemUtilities.setItems(ItemUtilities.java:202) ~[?:?]
 at me.RockinChaos.itemjoin.item.ItemUtilities.setAuthenticating(ItemUtilities.java:188) ~[?:?]
 at me.RockinChaos.itemjoin.listeners.triggers.WorldSwitch.setWorldSwitchItems(WorldSwitch.java:42) ~[?:?]
 at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
 at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
 at net.minecraft.server.v1_16_R3.PlayerList.moveToWorld(PlayerList.java:915) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
 at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.teleport(CraftPlayer.java:835) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
 at org.bukkit.craftbukkit.v1_16_R3.entity.CraftEntity.lambda$null$0(CraftEntity.java:562) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
 at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
 at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:151) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
 at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
 at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:114) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
 at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1204) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
 at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1197) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
 at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:97) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
 at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1337) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
 at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1012) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
 at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
 at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]`

**Comment by yurabens** [comment]
Config+Items: [config+items.zip](https://github.com/RockinChaos/ItemJoin/files/6016936/config%2Bitems.zip)

**Comment by RockinChaos** [comment]
Uhhhh sooo this is occurring because you are missing A LOT from your config.yml.
Specifically the clear-items section and active commands.


I simply just copied your current values from the config.yml to a fixed version.
Fixed config.yml; https://pastebin.com/JcTuA14q
