### ISSUE TITLE
what does the error mean?

### ISSUE THREAD

**Issue by yurabens** [RockinChaos/ItemJoin#374]
I see it occasionally in the console...

```
[16:33:19 INFO]: 94.25.174.140
 [16:33:19 INFO]: Sessions enabled
 [16:33:19 INFO]: Sessions validated
 [16:33:19 INFO]: Before return
 [16:33:19 INFO]: [HamsterAPI] Succesfully setup player wolfes!
 [16:33:19 INFO]: [HamsterAPI] Succesfully injected player wolfes!
 [16:33:19 INFO]: Игрок подключился к ламповой игре на «Бэнс RP»
 [16:33:20 WARN]: [ItemJoin] Plugin ItemJoin v5.2.1-RELEASE-b678 generated an exception while executing task 145095
java.lang.NullPointerException: null
 at me.RockinChaos.itemjoin.listeners.triggers.PlayerGuard.handleRegions(PlayerGuard.java:92) ~[?:?]
 at me.RockinChaos.itemjoin.listeners.triggers.PlayerGuard.lambda$setRegionItems$0(PlayerGuard.java:55) ~[?:?]
 at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
 at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
 at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.4.jar:git-Yatopia-"99e3c5d"]
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_282]
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_282]
 at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
```

**Comment by RockinChaos** [comment]
The latest snapshot should now resolve this issue.
Link; https://ci.craftationgaming.com/job/ItemJoin/684/
**Remember to remove your old ItemJoin.jar file**
