### ISSUE TITLE
Not working with GemsEconomy

### ISSUE THREAD

**Issue by Tanerx** [RockinChaos/ItemJoin#376]
**Describe the bug**
ItemJoin not working with GemsEconomy in some cases. 

**To Reproduce**
1. Itemjoin set to **MySQL: false**
2. GemsEconomy set to **storage: yaml**

Console error 
`[22:28:14 WARN]: [ItemJoin] Loaded class com.zaxxer.hikari.HikariConfig from GemsEconomy v4.9.2 which is not a depend, softdepend or loadbefore of this plugin.
[22:28:14 INFO]: [com.zaxxer.hikari.HikariDataSource] HikariPool-1 - Starting...
[22:28:14 WARN]: [ItemJoin] Plugin ItemJoin v5.2.1-RELEASE-b678 generated an exception while executing task 10
java.lang.NoSuchMethodError: com.zaxxer.hikari.HikariConfig.getKeepaliveTime()J
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:486) ~[?:?]
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) ~[?:?]
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115) ~[?:?]
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81) ~[?:?]
        at me.RockinChaos.itemjoin.utils.sql.Controller.getConnection(Database.java:455) ~[?:?]
        at me.RockinChaos.itemjoin.utils.sql.Database.getDatabase(Database.java:401) ~[?:?]
        at me.RockinChaos.itemjoin.utils.sql.SQL.alterTables(SQL.java:260) ~[?:?]
        at me.RockinChaos.itemjoin.utils.sql.SQL.createTables(SQL.java:239) ~[?:?]
        at me.RockinChaos.itemjoin.utils.sql.SQL.<init>(SQL.java:42) ~[?:?]
        at me.RockinChaos.itemjoin.utils.sql.SQL.newData(SQL.java:332) ~[?:?]
        at me.RockinChaos.itemjoin.handlers.ConfigHandler.lambda$registerClasses$2(ConfigHandler.java:128) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.5.jar:git-Paper-529]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-529]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-529]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_281]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_281]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]`

Cant join the server anymone. 

`com.mojang.authlib.GameProfile@67013ef8[id=b5df7cbb-688a-335e-854e-4cba1d3fc758,name=Taner,properties={},legacy=false] (/127.0.0.1:1163) lost connection: Disconnected`

3. Disable only Itemjoin and server is working fine.
---------------------------------------------------------------------------

1. Itemjoin set to **MySQL: false**
2. GemsEconomy set to **storage: mysql**
3. Server and both plugins working fine just one warn.
`[22:34:35 WARN]: [ItemJoin] Loaded class com.zaxxer.hikari.HikariConfig from GemsEconomy v4.9.2 which is not a depend, softdepend or loadbefore of this plugin.`

**Pastebin**
https://pastebin.com/XHLZZ1Hf   GemsEconomy without mysql
https://pastebin.com/KBUzgSVz GemsEconomy enabled mysql

**Please complete the following information:**
 - Resource Version and Build Number: [v5.2.1-RELEASE-b678]
 - Server Version [git-Paper-529 (MC: 1.16.5)]

**Additional context**
Should i have report to this GemsEconomy dev ? I did not know wich plugin have the bug.

**Comment by RockinChaos** [comment]
That is really weird, it looks like ItemJoin is trying to load the Hikari config from GemsEconomy but ItemJoin includes Hikari by default inside its own jar file.

Looking into this now, I should be able to let you know shortly.

**Comment by RockinChaos** [comment]
Okay, so I completely dropped Hikari entirely and just wrote my own API to handle the database so it should work now using the latest snapshot.

Link; https://ci.craftationgaming.com/job/ItemJoin/688/
**Remember to remove your old ItemJoin.jar file**

Let me know.

**Comment by Tanerx** [comment]
> Okay, so I completely dropped Hikari entirely and just wrote my own API to handle the database so it should work now using the latest snapshot.
> 
> Link; https://ci.craftationgaming.com/job/ItemJoin/688/
> **Remember to remove your old ItemJoin.jar file**
> 
> Let me know.

Itemjoin set to MySQL: false
GemsEconomy set to storage: yaml
Build #688  Both plugins working fine without any console error.

**Comment by RockinChaos** [comment]
This bug has been officially fixed in the release of ItemJoin v5.2.2.
You can grab it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=403809

Please read the changelog as the documentation has not been updated yet;
https://github.com/RockinChaos/ItemJoin/wiki/Recent-Changes
