### ISSUE TITLE
Dont work with PerWorldPlugins

### ISSUE THREAD

**Issue by HDPlayser** [RockinChaos/ItemJoin#39]
Hello,

I have on my server installed PerWorldPlugins (PWP). Now, I have there checked the option "Exempt-login-events: true"

Now, when I join, it shows that:

[13:45:25] [Server thread/ERROR]: **** THIS IS NOT AN ISSUE TO DO WITH PER WORLD PLUGINS ****Could not pass event PlayerJoinEvent to ItemJoin v3.0org.bukkit.event.EventExceptionat us.Myles.PWP.TransparentListeners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:122) ~[?:?]at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Bukkit.jar:git-Bukkit-18fbb24]at us.Myles.PWP.TransparentListeners.PWPRegisteredListener.callEvent(PWPRegisteredListener.java:30) [perworldplugins%20(1).jar:?]at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [Bukkit.jar:git-Bukkit-18fbb24]at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [Bukkit.jar:git-Bukkit-18fbb24]at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:282) [Bukkit.jar:git-Bukkit-18fbb24]at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:142) [Bukkit.jar:git-Bukkit-18fbb24]at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:115) [Bukkit.jar:git-Bukkit-18fbb24]at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:53) [Bukkit.jar:git-Bukkit-18fbb24]at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:222) [Bukkit.jar:git-Bukkit-18fbb24]at net.minecraft.server.v1_8_R3.ServerConnection.c(SourceFile:168) [Bukkit.jar:git-Bukkit-18fbb24]at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:745) [Bukkit.jar:git-Bukkit-18fbb24]at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:335) [Bukkit.jar:git-Bukkit-18fbb24]at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:629) [Bukkit.jar:git-Bukkit-18fbb24]at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:537) [Bukkit.jar:git-Bukkit-18fbb24]at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]Caused by: java.lang.NullPointerExceptionat me.RockinChaos.itemjoin.ItemJoin.CacheItems(ItemJoin.java:125) ~[?:?]at me.RockinChaos.itemjoin.Listeners.JoinItem.JoinItem.giveOnJoin(JoinItem.java:48) ~[?:?]at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_92]at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_92]at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_92]at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:120) ~[?:?]... 15 more

I have activated this plugin in some specific worlds:

  ItemJoin:
  - Games

**Comment by RockinChaos** [comment]
1.) Why use perworldplugin with ItemJoin? It can be deactivated/Activated per world. ItemJoin has complete and full world control and can be customized.

2.) Considering you are getting this error I am assuming you are on bukkit/spigot 1.8. Especially as I can see the version: net.minecraft.server.v1_8_R3.

The reason you are getting this error is because ItemJoin is trying to send console a message saying 1.9 mode has been disabled and offhand will no longer be used.

You get this error because in the items.yml you still have the offhand item defined. I have a system that prevents this error from revealing itself and will auto-disable the offhand item but for some reason perworldplugin does not like ItemJoin communicating with console.

I will look into seeing if this can be fixed but, it seems that perworldplugin might have to implement an api to allow plugins to communicate with console.

In the mean time you can try this fix: Find any item that has slot: offhand and remove it. Once the whole offhand item has been removed the error should no longer occur.

**Comment by HDPlayser** [comment]
Hello, 

thanks for the Reply I've done that, but it not worked. For any reason, I don't know the PLugin CustomjoinItems work. before it doesn't worked. I wrote him too, but I don't get a reply. anyway, very much thanks for the help.

**Comment by RockinChaos** [comment]
Please try v3.1 and see if this fixes it. If not reopen this issue.
http://dev.bukkit.org/bukkit-plugins/itemjoin/files/26-item-join-v3-1/
