### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by hlnebula** [RockinChaos/ItemJoin#393]
[14:47:42 INFO]: HL_Nebula issued server command: /hub
[14:47:42 WARN]: [ItemJoin] Task #69986 for ItemJoin v5.2.1-RELEASE-b678 generated an exception
java.lang.IllegalArgumentException: Cannot measure distance between hub and pvp_flat
        at org.bukkit.Location.distanceSquared(Location.java:510) ~[patched_1.16.5.jar:git-Paper-648]
        at org.bukkit.Location.distance(Location.java:493) ~[patched_1.16.5.jar:git-Paper-648]
        at me.RockinChaos.itemjoin.item.ItemMap.warmLocation(ItemMap.java:4249) ~[?:?]
        at me.RockinChaos.itemjoin.item.ItemMap.lambda$warmCycle$4(ItemMap.java:4209) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-648]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-648]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1423) ~[patched_1.16.5.jar:git-Paper-648]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:419) ~[patched_1.16.5.jar:git-Paper-648]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1338) ~[patched_1.16.5.jar:git-Paper-648]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1126) ~[patched_1.16.5.jar:git-Paper-648]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-648]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_291]

**Comment by hlnebula** [comment]
This happens when executing a command that teleports you while a command is warming up￼￼

**Comment by hlnebula** [comment]
https://drive.google.com/file/d/1wIAOxzb-LhQDIanY6JrLYsVCJO96lzBK/view?usp=sharing

**Comment by RockinChaos** [comment]
Resolved on Discord, latest snapshot fixes the issue.
