### ISSUE TITLE
SkinsRestorer error.

### ISSUE THREAD

**Issue by TheIntelloBox** [RockinChaos/ItemJoin#408]
Hello,

[17:42:23] [Server thread/WARN]: java.lang.NoSuchMethodException: net.skinsrestorer.bukkit.SkinsRestorer.getInstance()
[17:42:23] [Server thread/WARN]: 	at java.base/java.lang.Class.getMethod(Class.java:2195)
[17:42:23] [Server thread/WARN]: 	at me.RockinChaos.itemjoin.utils.api.DependAPI.getSkinValue(DependAPI.java:205)
[17:42:23] [Server thread/WARN]: 	at me.RockinChaos.itemjoin.handlers.ItemHandler.setStoredSkull(ItemHandler.java:417)
[17:42:23] [Server thread/WARN]: 	at me.RockinChaos.itemjoin.handlers.ItemHandler.setSkullOwner(ItemHandler.java:402)
[17:42:23] [Server thread/WARN]: 	at me.RockinChaos.itemjoin.item.ItemAnimation.setSkull(ItemAnimation.java:357)
[17:42:23] [Server thread/WARN]: 	at me.RockinChaos.itemjoin.item.ItemAnimation.lambda$AnimateTask$0(ItemAnimation.java:214)
[17:42:23] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100)
[17:42:23] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[17:42:23] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1488)
[17:42:23] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:477)
[17:42:23] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1404)
[17:42:23] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1180)
[17:42:23] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[17:42:23] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[17:42:32] [Server thread/WARN]: java.lang.NoSuchMethodException: net.skinsrestorer.bukkit.SkinsRestorer.getInstance()
[17:42:32] [Server thread/WARN]: 	at java.base/java.lang.Class.getMethod(Class.java:2195)
[17:42:32] [Server thread/WARN]: 	at me.RockinChaos.itemjoin.utils.api.DependAPI.getSkinValue(DependAPI.java:205)
[17:42:32] [Server thread/WARN]: 	at me.RockinChaos.itemjoin.handlers.ItemHandler.setStoredSkull(ItemHandler.java:417)
[17:42:32] [Server thread/WARN]: 	at me.RockinChaos.itemjoin.handlers.ItemHandler.setSkullOwner(ItemHandler.java:402)
[17:42:32] [Server thread/WARN]: 	at me.RockinChaos.itemjoin.item.ItemAnimation.setSkull(ItemAnimation.java:357)
[17:42:32] [Server thread/WARN]: 	at me.RockinChaos.itemjoin.item.ItemAnimation.lambda$AnimateTask$0(ItemAnimation.java:214)
[17:42:32] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100)
[17:42:32] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[17:42:32] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1488)
[17:42:32] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:477)
[17:42:32] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1404)
[17:42:32] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1180)
[17:42:32] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[17:42:32] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)

Paper 1.17 using SkinsRestorer 1.14.1.

**Comment by RockinChaos** [comment]
Hi, this was already fixed in v5.2.3 snapshots.
Please update to the latest snapshot.

Link; https://ci.craftationgaming.com/job/ItemJoin/738/
**Remember to remove your old ItemJoin.jar file**

**Comment by RockinChaos** [comment]
Officially fixed in the latest release,

You can now download it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=431799
