### ISSUE TITLE
I can't put a skin name in the heads

### ISSUE THREAD

**Issue by trocaum** [RockinChaos/ItemJoin#422]
SORRY FOR BAD ENGLISH
when i put skin name in head with skull-owner, the head stay normal being alex or steve and in the console appears [ItemJoin] The player <player> could not be found!

**Comment by RockinChaos** [comment]
Could you provide the item in question so I can check your settings.
Pastebin.com link of your items.yml would be ideal.

**Comment by SuggarHidden** [comment]
I have the same problem.

_Server version: PaperSpigot-"4c7641d" (MC: 1.8.8)
ItemJoin version: ItemJoin v5.2.2-RELEASE-b734 by RockinChaos
SkinsRestorer version: v14.1.3_

**Item config:** 
`  profile:
    id: SKULL_ITEM:3
    skull-owner: '%player%'
    slot: 1
    name: '&b%player%'
    lore:
    - '&7Great for setting a players profile,'
    - '&7as seen in mini-game servers.'
    itemflags: inventory-modify, death-drops, unbreakable, hide-durability, hide-attributes, self-drops, overwrite, item-store
    triggers: join, respawn, world-change
    enabled-worlds: ALL`
    
    **Console error:** 
    `[01:29:33 WARN]: java.lang.NoSuchMethodException: net.skinsrestorer.bukkit.SkinsRestorer.getInstance()
[01:29:33 WARN]:        at java.lang.Class.getMethod(Unknown Source)
[01:29:33 WARN]:        at me.RockinChaos.itemjoin.utils.api.DependAPI.getSkinValue(DependAPI.java:205)
[01:29:33 WARN]:        at me.RockinChaos.itemjoin.handlers.ItemHandler.setStoredSkull(ItemHandler.java:417)
[01:29:33 WARN]:        at me.RockinChaos.itemjoin.handlers.ItemHandler.setSkullOwner(ItemHandler.java:402)
[01:29:33 WARN]:        at me.RockinChaos.itemjoin.item.ItemMap.setSkull(ItemMap.java:3980)
[01:29:33 WARN]:        at me.RockinChaos.itemjoin.item.ItemMap.updateItem(ItemMap.java:3599)
[01:29:33 WARN]:        at me.RockinChaos.itemjoin.item.ItemMap.getItem(ItemMap.java:3575)
[01:29:33 WARN]:        at me.RockinChaos.itemjoin.item.ItemUtilities.lambda$setInvSlots$5(ItemUtilities.java:568)
[01:29:33 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[01:29:33 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352)
[01:29:33 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783)
[01:29:33 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[01:29:33 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
[01:29:33 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
[01:29:33 WARN]:        at java.lang.Thread.run(Unknown Source)`

**Comment by RockinChaos** [comment]
Officially fixed in the latest release,

You can now download it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=431799
