### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by RageTVOfficial** [RockinChaos/ItemJoin#439]
Hey i have a problem! Console is showing this error and idk what it is
```
io.netty.channel.ChannelPipelineException: me.RockinChaos.itemjoin.utils.protocol.TinyProtocol$3 is not a @Sharable handler, so can't be added or removed multiple times.
at io.netty.channel.DefaultChannelPipeline.checkMultiplicity(DefaultChannelPipeline.java:600) ~[patched_1.17.1.jar:git-Tuinity-"4c31ea1"]
at io.netty.channel.DefaultChannelPipeline.addFirst(DefaultChannelPipeline.java:159) ~[patched_1.17.1.jar:git-Tuinity-"4c31ea1"]
at io.netty.channel.DefaultChannelPipeline.addFirst(DefaultChannelPipeline.java:358) ~[patched_1.17.1.jar:git-Tuinity-"4c31ea1"]
at io.netty.channel.DefaultChannelPipeline.addFirst(DefaultChannelPipeline.java:339) ~[patched_1.17.1.jar:git-Tuinity-"4c31ea1"]
at me.RockinChaos.itemjoin.utils.protocol.TinyProtocol.registerChannelHandler(TinyProtocol.java:200) ~[ItemJoin.jar:?]
at me.RockinChaos.itemjoin.utils.protocol.TinyProtocol.<init>(TinyProtocol.java:110) ~[ItemJoin.jar:?]
at me.RockinChaos.itemjoin.utils.protocol.ProtocolManager$1.<init>(ProtocolManager.java:44) ~[ItemJoin.jar:?]
at me.RockinChaos.itemjoin.utils.protocol.ProtocolManager.handleProtocols(ProtocolManager.java:44) ~[ItemJoin.jar:?]
at me.RockinChaos.itemjoin.handlers.ConfigHandler.registerListeners(ConfigHandler.java:643) ~[ItemJoin.jar:?]
at me.RockinChaos.itemjoin.item.ItemDesigner.<init>(ItemDesigner.java:123) ~[ItemJoin.jar:?]
at me.RockinChaos.itemjoin.item.ItemDesigner.getDesigner(ItemDesigner.java:1257) ~[ItemJoin.jar:?]
at me.RockinChaos.itemjoin.handlers.ConfigHandler.lambda$registerClasses$1(ConfigHandler.java:135) ~[ItemJoin.jar:?]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Tuinity-"4c31ea1"]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Tuinity-"4c31ea1"]
at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1550) ~[patched_1.17.1.jar:git-Tuinity-"4c31ea1"]
at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:480) ~[patched_1.17.1.jar:git-Tuinity-"4c31ea1"]
at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1465) ~[patched_1.17.1.jar:git-Tuinity-"4c31ea1"]
at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1261) ~[patched_1.17.1.jar:git-Tuinity-"4c31ea1"]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[patched_1.17.1.jar:git-Tuinity-"4c31ea1"]
at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by RockinChaos** [comment]
Already resolved in the latest snapshot;
Link; https://ci.craftationgaming.com/job/ItemJoin/781/
**Remember to remove your old ItemJoin.jar file**

Also, please review the changes from the latest release to this current snapshot;
https://github.com/RockinChaos/ItemJoin/wiki/DevLog

**Comment by RockinChaos** [comment]
I am marking this a resolved due to inactivity, this issue is already resolved in the latest release so I would start there. Feel free to reach out if you still need additional help.

You can now download it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=431799
