### ISSUE TITLE
When I Configurated An A Item When I Join it gives me nothing

### ISSUE THREAD

**Issue by zNexus90** [RockinChaos/ItemJoin#472]
## Thanks for taking the time to open a bug report!

**Describe the bug**
[17:37:17 ERROR]: **** THIS IS NOT AN ISSUE TO DO WITH PER WORLD PLUGINS ****
Could not pass event InventoryClickEvent to ItemJoin v5.2.3-RELEASE-b789
org.bukkit.event.EventException
        at me.incomprehendable.dev.pwp.transparentlisteners.PerWorldPluginLoader.lambda$createRegisteredListeners$1(PerWorldPluginLoader.java:113) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
        at me.incomprehendable.dev.pwp.transparentlisteners.PWPRegisteredListener.callEvent(PWPRegisteredListener.java:20) [PerWorldPlugins%201.0.1.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:1588) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.PacketPlayInWindowClick.a(SourceFile:31) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.PacketPlayInWindowClick.a(SourceFile:9) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_201]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_201]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_201]
        at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_201]
        at me.RockinChaos.itemjoin.utils.interfaces.Page.chatEvent(Page.java:132) ~[?:?]
        at me.RockinChaos.itemjoin.utils.interfaces.Interface.onClick(Interface.java:99) ~[?:?]
        at me.RockinChaos.itemjoin.listeners.Interfaces.onClick(Interfaces.java:48) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor60.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
        at me.incomprehendable.dev.pwp.transparentlisteners.PerWorldPluginLoader.lambda$createRegisteredListeners$1(PerWorldPluginLoader.java:110) ~[?:?]
        ... 15 more
[17:37:52 ERROR]: [ItemJoin] Unhandled exception occured in onPacketReceiving(PacketEvent) for ItemJoin
java.lang.NoSuchFieldError: AUTO_RECIPE
        at me.RockinChaos.itemjoin.utils.api.ProtocolAPI$1.onPacketReceiving(ProtocolAPI.java:65) ~[ItemJoin.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:4.0.2-b303]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:4.0.2-b303]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:610) [ProtocolLib.jar:4.0.2-b303]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:577) [ProtocolLib.jar:4.0.2-b303]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:323) [ProtocolLib.jar:4.0.2-b303]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:288) [ProtocolLib.jar:4.0.2-b303]
        at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:541) [ProtocolLib.jar:4.0.2-b303]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:241) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:273) [ProtocolLib.jar:4.0.2-b303]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:507) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:464) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:378) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:350) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
[17:37:52 ERROR]: Parameters:
  net.minecraft.server.v1_8_R1.PacketPlayInCloseWindow@7718ce3e[
    id=17
  ]

[17:37:54 INFO]: rnardy issued server command: /kits
[17:37:55 ERROR]: [ItemJoin] Unhandled exception occured in onPacketReceiving(PacketEvent) for ItemJoin
java.lang.NoSuchFieldError: AUTO_RECIPE
        at me.RockinChaos.itemjoin.utils.api.ProtocolAPI$1.onPacketReceiving(ProtocolAPI.java:65) ~[ItemJoin.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:4.0.2-b303]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:4.0.2-b303]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:610) [ProtocolLib.jar:4.0.2-b303]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:577) [ProtocolLib.jar:4.0.2-b303]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:323) [ProtocolLib.jar:4.0.2-b303]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:288) [ProtocolLib.jar:4.0.2-b303]
        at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:541) [ProtocolLib.jar:4.0.2-b303]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:241) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:273) [ProtocolLib.jar:4.0.2-b303]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:507) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:464) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:378) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:350) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
[17:37:55 ERROR]: Parameters:
  net.minecraft.server.v1_8_R1.PacketPlayInCloseWindow@8d13730[
    id=18
  ]

[17:38:00 INFO]: rnardy issued server command: /kits
[17:38:01 ERROR]: [ItemJoin] Unhandled exception occured in onPacketReceiving(PacketEvent) for ItemJoin
java.lang.NoSuchFieldError: AUTO_RECIPE
        at me.RockinChaos.itemjoin.utils.api.ProtocolAPI$1.onPacketReceiving(ProtocolAPI.java:65) ~[ItemJoin.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:4.0.2-b303]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:4.0.2-b303]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:610) [ProtocolLib.jar:4.0.2-b303]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:577) [ProtocolLib.jar:4.0.2-b303]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:323) [ProtocolLib.jar:4.0.2-b303]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:288) [ProtocolLib.jar:4.0.2-b303]
        at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:541) [ProtocolLib.jar:4.0.2-b303]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:241) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:273) [ProtocolLib.jar:4.0.2-b303]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:507) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:464) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:378) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:350) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
[17:38:01 ERROR]: Parameters:
  net.minecraft.server.v1_8_R1.PacketPlayInCloseWindow@16d5ad6d[
    id=19
  ]

 - Server Version [eSpigot-1.8]

**Additional context**

**Comment by RockinChaos** [comment]
Sorry for the late reply, I have been severely sick the past few days.

The referenced issue looks to already be resolved in the latest snapshot.
See; https://ci.craftationgaming.com/job/ItemJoin/812/
**Remember to remove your old ItemJoin.jar file**

**Comment by RockinChaos** [comment]
Officially fixed in the latest release,

You can now download it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=451699
