### ISSUE TITLE
NullPointerException: Cannot invoke "String.equalsIgnoreCase(String)"

### ISSUE THREAD

**Issue by mibby** [RockinChaos/ItemJoin#492]
**Describe the bug**
```
[18:42:16] [Craft Scheduler Thread - 2609 - ItemJoin/WARN]: [ItemJoin] Plugin ItemJoin v5.2.5-SNAPSHOT-b846 generated an exception while executing task 1376850
java.lang.NullPointerException: Cannot invoke "String.equalsIgnoreCase(String)" because the return value of "me.RockinChaos.itemjoin.handlers.ItemHandler.getNBTData(org.bukkit.inventory.ItemStack)" is null
	at me.RockinChaos.itemjoin.item.ItemMap.isReal(ItemMap.java:3639) ~[ItemJoin-5.2.5-SNAPSHOT-b846.jar:?]
	at me.RockinChaos.itemjoin.item.ItemAnimation.lambda$AnimateTask$5(ItemAnimation.java:211) ~[ItemJoin-5.2.5-SNAPSHOT-b846.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.2.jar:git-Purpur-1755]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.2.jar:git-Purpur-1755]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.2.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Pastebin**
Config - https://paste.gg/p/anonymous/ec706eecd4894fb0aef5ae7fd4268948/files/e7faed2e0b974e8ebdcd95ecbaee7d25/raw
Items - https://paste.gg/p/anonymous/960a763403ce446684e038a06ca18d80/files/52c05737d5944348bb3a1e88b6077c0d/raw

**Please complete the following information:**
 - ItemJoin dev 846
- Purpur dev 1755 (Paper 1.19.2)

**Comment by RockinChaos** [comment]
Looks specific to 1.19.2, stay tuned for a supporting snapshot (soonish).

**Comment by RockinChaos** [comment]
The latest snapshot should now address this issue.
Link; https://ci.craftationgaming.com/job/ItemJoin/847/
**Remember to remove your old ItemJoin.jar file**

**Comment by RockinChaos** [comment]
Officially fixed in the latest release,

You can now download it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=467409
