### ISSUE TITLE
ItemJoin 1.21 Support

### ISSUE THREAD

**Issue by ImGGAAVVIINN** [RockinChaos/ItemJoin#597]
### Server Version

Spigot 1.21

### Resource Version

ItemJoin-v6.0.7-RELEASE

### Dump Information

cannot dump, plugin crash on start

### Describe The Bug

Item Join crashes on startup and was disabled

[15:53:51] [Server thread/INFO]: [ItemJoin] Enabling ItemJoin v6.0.7-RELEASE-b995
[15:53:51] [Server thread/ERROR]: [ItemJoin_ERROR] detected incompatible server version.
[15:53:51] [Server thread/ERROR]: [ItemJoin_ERROR] only Minecraft 1.8 and above is supported.
[15:53:51] [Server thread/ERROR]: [ItemJoin_ERROR] disabling...
[15:53:51] [Server thread/INFO]: [ItemJoin] Disabling ItemJoin v6.0.7-RELEASE-b995
[15:53:52] [Server thread/ERROR]: [ItemJoin_ERROR] {SQL} SQLite exception on initialize.
[15:53:52] [Server thread/WARN]: java.sql.SQLException: path to '/home/ascend/MinecraftServers/Paper/plugins/ItemJoin/database.db': '/home/ascend/MinecraftServers/Paper/plugins/ItemJoin' does not exist
[15:53:52] [Server thread/WARN]:        at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:261)
[15:53:52] [Server thread/WARN]:        at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:67)
[15:53:52] [Server thread/WARN]:        at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28)
[15:53:52] [Server thread/WARN]:        at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:19)
[15:53:52] [Server thread/WARN]:        at org.sqlite.JDBC.createConnection(JDBC.java:106)
[15:53:52] [Server thread/WARN]:        at org.sqlite.JDBC.connect(JDBC.java:79)
[15:53:52] [Server thread/WARN]:        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
[15:53:52] [Server thread/WARN]:        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:253)
[15:53:52] [Server thread/WARN]:        at me.RockinChaos.itemjoin.core.utils.sql.Controller.getConnection(Database.java:441)
[15:53:52] [Server thread/WARN]:        at me.RockinChaos.itemjoin.core.utils.sql.Database.getDatabase(Database.java:68)
[15:53:52] [Server thread/WARN]:        at me.RockinChaos.itemjoin.ItemJoin.onDisable(ItemJoin.java:84)
[15:53:52] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:269)
[15:53:52] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:367)
[15:53:52] [Server thread/WARN]:        at me.RockinChaos.itemjoin.core.Core.isEnabled(Core.java:77)
[15:53:52] [Server thread/WARN]:        at me.RockinChaos.itemjoin.ItemJoin.onEnable(ItemJoin.java:59)
[15:53:52] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267)
[15:53:52] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[15:53:52] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:492)
[15:53:52] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugin(CraftServer.java:567)
[15:53:52] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugins(CraftServer.java:481)
[15:53:52] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:237)
[15:53:52] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1017)
[15:53:52] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[15:53:52] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)

### Expected Behavior

The plugin should be updated to 1.21

### Steps To Reproduce

1. install plugin to latest spigot 1.21
2. start server
3. itemjoin crashes

### Checklist

- [X] I am running latest version of this resource.
- [X] I have read the wiki to make sure it's not an issue with configuration.
- [ ] I ticked all of these boxes without actually reading them.
- [X] I have checked that my bug report is unique and a previous report does not exist.

**Comment by RockinChaos** [comment]
This is expected, the release version is specifically stated to only support up to 1.20.6.

![image](https://github.com/RockinChaos/ItemJoin/assets/10971577/db730af4-42f5-4b36-9391-6f1f67c48b1e)


As stated on the resource page, you can get the 1.21 supported snapshots here;
Link; https://ci.craftationgaming.com/downloads
**Remember to remove your old ItemJoin.jar file**

**Comment by ImGGAAVVIINN** [comment]
Found it! thanks for helping :D
