### ISSUE TITLE
Save config error

### ISSUE THREAD

**Issue by jugandomiguel** [RockinChaos/ItemJoin#608]
### Server Version

ShieldSpigot version 1.21.1-DEV-ver/1.21@9a82b86 (2024-08-24T12:52:35Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

### Resource Version

ItemJoin v6.1.0-RELEASE-b1031

### Dump Information

https://ci.craftationgaming.com/dump?id=hofequgalo

### Describe The Bug

When trying to save using the ij menu it sends an exception to the console and don't save the new item config

### Expected Behavior

Save new config made by gui to the items.yml

### Steps To Reproduce

1. Modify the item by gui (ij menu)
2. Change triggers
3. Click save to config in item config menu
4. Click main menu button
5. Save to config again
6. Error achieved!

### Additional Info

[15:33:25 WARN]: [ItemJoin] Task #925646 for ItemJoin v6.1.0-RELEASE-b1031 generated an exception
java.lang.NullPointerException: Cannot invoke "String.contains(java.lang.CharSequence)" because "this.count" is null
        at ItemJoin.jar/me.RockinChaos.itemjoin.item.ItemMap.parseData_1(ItemMap.java:5894) ~[ItemJoin.jar:?]
        at ItemJoin.jar/me.RockinChaos.itemjoin.item.ItemMap.saveToConfig(ItemMap.java:6455) ~[ItemJoin.jar:?]
        at ItemJoin.jar/me.RockinChaos.itemjoin.utils.menus.Menu.lambda$creatingPane$119(Menu.java:1092) ~[ItemJoin.jar:?]
        at ItemJoin.jar/me.RockinChaos.itemjoin.core.utils.interfaces.types.Button.lambda$onClick$1(Button.java:147) ~[ItemJoin.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[?:?]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1733) ~[shieldspigot%201.21.1-1.21.1.jar:1.21.1-DEV-9a82b86]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:476) ~[shieldspigot%201.21.1-1.21.1.jar:1.21.1-DEV-9a82b86]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1605) ~[shieldspigot%201.21.1-1.21.1.jar:1.21.1-DEV-9a82b86]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1305) ~[shieldspigot%201.21.1-1.21.1.jar:1.21.1-DEV-9a82b86]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:331) ~[shieldspigot%201.21.1-1.21.1.jar:1.21.1-DEV-9a82b86]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

### Checklist

- [X] I am running latest version of this resource.
- [X] I have read the wiki to make sure it's not an issue with configuration.
- [ ] I ticked all of these boxes without actually reading them.
- [X] I have checked that my bug report is unique and a previous report does not exist.

**Comment by RockinChaos** [comment]
Confirmed and fixed in the latest snapshot.

Thanks for letting me know!
Link; https://ci.craftationgaming.com/downloads
**Remember to remove your old ItemJoin.jar file**

Let me know!~
