### ISSUE TITLE
Getting errors in the console

### ISSUE THREAD

**Issue by miryaev** [RockinChaos/ItemJoin#609]
### Server Version

PaperSpigot 1.16.5

### Resource Version

ItemJoin v6.1.1 b1035

### Dump Information

https://ci.craftationgaming.com/dump/?id=exusigaxeg

### Describe The Bug

> [20:38:46 ERROR]: [ItemJoin_ERROR] {CompatUtils} An error has occurred with InventoryView#getTitle!
> [20:38:46 WARN]: java.lang.reflect.InvocationTargetException
> [20:38:46 WARN]:        at jdk.internal.reflect.GeneratedMethodAccessor60.invoke(Unknown Source)
> [20:38:46 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [20:38:46 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> [20:38:46 WARN]:        at me.RockinChaos.itemjoin.core.utils.CompatUtils.getInventoryTitle(CompatUtils.java:139)
> [20:38:46 WARN]:        at me.RockinChaos.itemjoin.utils.menus.Menu.isOpen(Menu.java:9538)
> [20:38:46 WARN]:        at me.RockinChaos.itemjoin.item.ItemMap.executeCommands(ItemMap.java:5170)
> [20:38:46 WARN]:        at me.RockinChaos.itemjoin.listeners.Commands.lambda$runCommands$2(Commands.java:521)
> [20:38:46 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101)
> [20:38:46 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
> [20:38:46 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
> [20:38:46 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
> [20:38:46 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
> [20:38:46 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
> [20:38:46 WARN]: Caused by: java.util.ConcurrentModificationException
> [20:38:46 WARN]:        at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
> [20:38:46 WARN]:        at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)
> [20:38:46 WARN]:        at net.minecraft.server.v1_16_R3.ChatMessage.b(SourceFile:145)
> [20:38:46 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.util.CraftChatMessage.fromComponent(CraftChatMessage.java:357)
> [20:38:46 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftInventoryView.getTitle(CraftInventoryView.java:76)
> [20:38:46 WARN]:        ... 13 more
> [20:38:46 WARN]: [ItemJoin] Plugin ItemJoin v6.1.1-SNAPSHOT-b1035 generated an exception while executing task 765816
> java.lang.RuntimeException: org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer
>         at me.RockinChaos.itemjoin.core.utils.CompatUtils.getInventoryTitle(CompatUtils.java:143) ~[?:?]
>         at me.RockinChaos.itemjoin.utils.menus.Menu.isOpen(Menu.java:9538) ~[?:?]
>         at me.RockinChaos.itemjoin.item.ItemMap.executeCommands(ItemMap.java:5170) ~[?:?]
>         at me.RockinChaos.itemjoin.listeners.Commands.lambda$runCommands$2(Commands.java:521) ~[?:?]
>         at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Paper-794]
>         at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-794]
>         at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-794]
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
>         at java.lang.Thread.run(Thread.java:840) [?:?]
> Caused by: java.lang.reflect.InvocationTargetException
>         at jdk.internal.reflect.GeneratedMethodAccessor60.invoke(Unknown Source) ~[?:?]
>         at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
>         at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
>         at me.RockinChaos.itemjoin.core.utils.CompatUtils.getInventoryTitle(CompatUtils.java:139) ~[?:?]
>         ... 9 more
> Caused by: java.util.ConcurrentModificationException
>         at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013) ~[?:?]
>         at java.util.ArrayList$Itr.next(ArrayList.java:967) ~[?:?]
>         at net.minecraft.server.v1_16_R3.ChatMessage.b(SourceFile:145) ~[patched_1.16.5.jar:git-Paper-794]
>         at org.bukkit.craftbukkit.v1_16_R3.util.CraftChatMessage.fromComponent(CraftChatMessage.java:357) ~[patched_1.16.5.jar:git-Paper-794]
>         at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftInventoryView.getTitle(CraftInventoryView.java:76) ~[patched_1.16.5.jar:git-Paper-794]
>         at jdk.internal.reflect.GeneratedMethodAccessor60.invoke(Unknown Source) ~[?:?]
>         at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
>         at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
>         at me.RockinChaos.itemjoin.core.utils.CompatUtils.getInventoryTitle(CompatUtils.java:139) ~[?:?]
>         ... 9 more

### Expected Behavior

There shouldn't be so much text in the console window :)

### Steps To Reproduce

I don't understand what exactly leads to such errors

### Checklist

- [X] I am running latest version of this resource.
- [X] I have read the wiki to make sure it's not an issue with configuration.
- [ ] I ticked all of these boxes without actually reading them.
- [X] I have checked that my bug report is unique and a previous report does not exist.

**Comment by RockinChaos** [comment]
It's possible it's related but I don't think its because of AuthMe directly.
Seems to potentially be ConcurrentModificationException, give me a bit to bug test and I'll let you know when a snapshot is available containing a fix for this.

**Comment by RockinChaos** [comment]
Hey, sorry for the long wait. I implemented some changes that should resolve this issue.
I could never replicate it myself so I made some educated guesses based of the error you submitted.

Link; https://ci.craftationgaming.com/downloads
**Remember to remove your old ItemJoin.jar file**

Let me know!~
