### ISSUE TITLE
Missing the most important thing

### ISSUE THREAD

**Issue by Mayr3D** [RockinChaos/ItemJoin#64]
Hello,
i was using custom join items
and it was wonderful for me but unfortunately doesn't support skull owner.
--
but u also doesn't support the disabling worlds like them everytime i switch to another world i see the item of that world in world2.
custom join items was able to remove the previous items without removing all the inventories! only the join items
soo, if u can do that it would be helpful for me and for other ppl :D

**Comment by RockinChaos** [comment]
This is something I am adding to v3.7 which should be out soon. I am waiting for new computer parts that come in tomorrow and I will be getting to work on it. ;)

**Comment by Mayr3D** [comment]
:DDD Thank You

**Comment by Mayr3D** [comment]
Cant wait :santa:

**Comment by Mayr3D** [comment]
Still Wait :(

**Comment by RockinChaos** [comment]
Currently working on coding this part for v3.7 and once its done it will be available for release, I am working on reducing the length of the code so it doesn't lag when removing the items from the players inventory.

**Comment by RockinChaos** [comment]
I have officially finished this, I am currently cleaning up the new config options and then it will be ready for release. It should be out late tomorrow (9/20/16) or early the day after (9/21/16). I am pushing to get this out as quick as possible.

**Comment by RockinChaos** [comment]
ItemJoin v3.7 has been released and you can get it here;
https://www.spigotmc.org/resources/itemjoin.12661/download?version=115467

This has been added as of v3.7 :D

**Comment by Mayr3D** [comment]
<33333333333333 i really loved hope its working will check it out

**Comment by Mayr3D** [comment]
i dont see ..
Added clear-on-join itemflag, clears the item from your inventory upon joining the server, before ItemJoin gives the items.
Added clear-on-world-change itemflag, removes the item from the players inventory upon leaving the world. in the items.yml

**Comment by RockinChaos** [comment]
It's under the global settings in the new config.
You can also use item flags on the items and put clear-on-join or clear-on-world-change

**Comment by Mayr3D** [comment]
its the same even in the new config i'll show you
---
Global-Settings: #// Global Settings, for each world listed under world-list. These will take effect in them. //#
  Prevention:
    prevent-pickups: false #// Prevents picking up of any item //#
    AllowOPBypass: false #// Ignores these settings under Prevention if you are OP //#
    CreativeBypass: false #// Ignores these settings under Prevention if you are in creative mode. //#
  Clear-On:
    clear-on-join: false #// Clears the players inventory upon entering the server. (Before items are given). //#
    clear-on-world-change: false #// Clears the players inventory upon changing worlds. (Before items are given). //#
    AllowOPBypass: false #// Ignores these settings under Clear-On if you are OP //#
  First-Join:
    FirstJoin-Mode-Enabled: false #// Set to true if you wish to use First-Join-Item: true per item! (This allows the use of the First Join options). //#
  Get-Items:
    ItemJoin-Specific-Items: true #// This meaning, these items are specific to ItemJoin and cannot be renamed to. Usually you would disable this if you had another plugin that hooks into ItemJoin items. //#
    Global-Items: false #// Setting this to true will make it so you can define items to work on ALL worlds listed under world-list. This means instead of defining a world for each world listed under world-list, you would simply just use the text global in  place of world name. //#
    Delay: 2 #// Set to 0 to disable. Recommended is 2 especially if you use First-Join! (This is in Seconds.) //#

**Comment by Mayr3D** [comment]
even the itemflags not working

**Comment by RockinChaos** [comment]
you didnt download v3.7 then, the items-version should be 5
https://www.spigotmc.org/resources/itemjoin.12661/download?version=115467

**Comment by RockinChaos** [comment]
Type /itemjoin and tell me what version it says it is.

**Comment by Mayr3D** [comment]
the version in the config says 4 
in the game says 3.6 and i already downloaded the latest version

**Comment by Mayr3D** [comment]
will try ur website and download from there

**Comment by Mayr3D** [comment]
its also 3.6 
dont tell me cuz i'm running 1.8.8 server :(

**Comment by RockinChaos** [comment]
Ohhh shoot I uploaded the wrong jar!

Reuploaded with correct jar. This is v3.7 download here;
https://www.spigotmc.org/resources/itemjoin.12661/download?version=115481

**Comment by Mayr3D** [comment]
xDDDD i knew it no problem thank you 

will try it

**Comment by Mayr3D** [comment]
yah its 3.7 now dont forget to edit in bukkit

**Comment by Mayr3D** [comment]
Its working very good but there is a bug :S
example : world 2 gives item in slot 5
in world 1 slot 5 was 5 stones blocks
its delete the 5 stones and replace it with itemjoin, it didnt swab the 5 stones to another slot

**Comment by RockinChaos** [comment]
Im confused I dont understand.

**Comment by Mayr3D** [comment]
Ammm
u were mining and got 5 diamond in slot 5 in the inventory 
then u changed ur world to another world that have itemjoin in slot5
it will delete the 5 diamonds and replaced by itemjoin.
its better if it change the place of 5 diamond in anyother slots

**Comment by Mayr3D** [comment]
the only thing i can do now its to put all the itemjoin in the same slot in other worlds

**Comment by RockinChaos** [comment]
You will need to use
      slot: Arbitrary
otherwise its going to place the item in the slot you told it to.
      slot: Arbitrary puts the item in the next available slot in the players inventory.

**Comment by Mayr3D** [comment]
oh cool how ?

**Comment by RockinChaos** [comment]
i just said use Arbitrary instead of the slot # literally put slot: Arbitrary instead of like slot: 0

**Comment by Mayr3D** [comment]
oh i understand now sorry
look at this found it in console 
about perworldplugin
its error and its says this is not an issue ..... couldnt copy it

**Comment by RockinChaos** [comment]
if you can copy it then Ill be able to help you

**Comment by Mayr3D** [comment]
i cant how can i do it its spamming most of time

**Comment by Mayr3D** [comment]
it happened when i change worlds

**Comment by RockinChaos** [comment]
open up your server logs and copy it

**Comment by Mayr3D** [comment]
[06:57:35] [Server thread/ERROR]: **** THIS IS NOT AN ISSUE TO DO WITH PER WORLD PLUGINS ****
Could not pass event PlayerChangedWorldEvent to ItemJoin v3.7
org.bukkit.event.EventException
	at me.incomprehendable.dev.pwp.transparentlisteners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:118) ~[?:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot-1.8.8-R0.1.jar:git-Spigot-db6de12-18fbb24]
	at me.incomprehendable.dev.pwp.transparentlisteners.PWPRegisteredListener.callEvent(PWPRegisteredListener.java:28) [PerWorldPlugins.jar:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [Spigot-1.8.8-R0.1.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [Spigot-1.8.8-R0.1.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerList.moveToWorld(PlayerList.java:628) [Spigot-1.8.8-R0.1.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.teleport(CraftPlayer.java:471) [Spigot-1.8.8-R0.1.jar:git-Spigot-db6de12-18fbb24]
	at com.earth2me.essentials.Teleport.now(Teleport.java:126) [Essentials-2.x-SNAPSHOT.jar:?]
	at com.earth2me.essentials.Teleport.teleport(Teleport.java:194) [Essentials-2.x-SNAPSHOT.jar:?]
	at com.earth2me.essentials.Teleport.warp(Teleport.java:263) [Essentials-2.x-SNAPSHOT.jar:?]
	at com.earth2me.essentials.commands.Commandwarp.warpUser(Commandwarp.java:130) [Essentials-2.x-SNAPSHOT.jar:?]
	at com.earth2me.essentials.commands.Commandwarp.run(Commandwarp.java:51) [Essentials-2.x-SNAPSHOT.jar:?]
	at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:180) [Essentials-2.x-SNAPSHOT.jar:?]
	at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:527) [Essentials-2.x-SNAPSHOT.jar:?]
	at com.earth2me.essentials.Essentials.onCommand(Essentials.java:402) [Essentials-2.x-SNAPSHOT.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [Spigot-1.8.8-R0.1.jar:git-Spigot-db6de12-18fbb24]
	at me.incomprehendable.dev.pwp.FakeSimpleCommandMap.dispatch(FakeSimpleCommandMap.java:98) [PerWorldPlugins.jar:?]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) [Spigot-1.8.8-R0.1.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [Spigot-1.8.8-R0.1.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [Spigot-1.8.8-R0.1.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [Spigot-1.8.8-R0.1.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [Spigot-1.8.8-R0.1.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot-1.8.8-R0.1.jar:git-Spigot-db6de12-18fbb24]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_77]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_77]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [Spigot-1.8.8-R0.1.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [Spigot-1.8.8-R0.1.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [Spigot-1.8.8-R0.1.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [Spigot-1.8.8-R0.1.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [Spigot-1.8.8-R0.1.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_77]
Caused by: java.lang.NoSuchMethodError: org.bukkit.inventory.PlayerInventory.getItemInOffHand()Lorg/bukkit/inventory/ItemStack;
	at me.RockinChaos.itemjoin.Listeners.JoinItem.JoinItem.clearInventory(JoinItem.java:132) ~[?:?]
	at me.RockinChaos.itemjoin.Listeners.JoinItem.JoinItem.clearItemJoinOnly(JoinItem.java:118) ~[?:?]
	at me.RockinChaos.itemjoin.Listeners.JoinItem.ChangedWorld.clearOnWorldChanged(ChangedWorld.java:27) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_77]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_77]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_77]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_77]
	at me.incomprehendable.dev.pwp.transparentlisteners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:116) ~[?:?]
	... 30 more

**Comment by Mayr3D** [comment]
and first-join it always comes when i join the server not in the first join only

**Comment by Mayr3D** [comment]
and Arbitrary would be better if it for the rest of items not item join just an idea

**Comment by RockinChaos** [comment]
ItemJoin does not store data from the other items, ItemJoin only deals with ItemJoin items, and we are staying an items on join plugin, we wont fiddle with current items in a players inventory so Arbitrary wouldnt be able to be applied to them.

first-join does work because you probably didnt enable it in the Global-Settings as well. You must set the boolean to true there and add the first-join itemflag to the items you want to get on first join only.

You are getting the PerWorldPlugins error because I forgot to add a check to itemjoin to make sure it doesnt use v1.9 combat mechanics in v 1.8.8. This is an error that will do no harm it will just spam the console. Once I get a bit more feedback from the new update and the rest of the bug reports from it I will publish a fix for this. ( But as it is the error from PWP causes no issues to the server or plugin itself. )

**Comment by Mayr3D** [comment]
Aha, Ok thank you very much 
and very sorry if i'm annoying xD

**Comment by RockinChaos** [comment]
Your not, I need the feedback so I can get everything fixed.

**Comment by Mayr3D** [comment]
Ok :D

**Comment by Mayr3D** [comment]
there is a bug in the new update 3.8 while clearing the other item on the same slot wont come while clearing on world change
[ItemJoin] Task #539 for ItemJoin v3.8 generated an exception
java.lang.NoSuchMethodError: org.bukkit.inventory.PlayerInventory.getItemInOffHand()Lorg/bukkit/inventory/ItemStack;
	at me.RockinChaos.itemjoin.utils.CheckItem.setOffhand(CheckItem.java:196) ~[?:?]
	at me.RockinChaos.itemjoin.Listeners.JoinItem.JoinItem.clearItemJoinItems(JoinItem.java:103) ~[?:?]
	at me.RockinChaos.itemjoin.Listeners.JoinItem.JoinItem.setClearItems(JoinItem.java:82) ~[?:?]
	at me.RockinChaos.itemjoin.Listeners.JoinItem.ChangedWorld$1.run(ChangedWorld.java:31) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[Spigot-1.8.8-R0.1.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [Spigot-1.8.8-R0.1.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [Spigot-1.8.8-R0.1.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [Spigot-1.8.8-R0.1.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [Spigot-1.8.8-R0.1.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [Spigot-1.8.8-R0.1.jar:git-Spigot-db6de12-18fbb24]

**Comment by RockinChaos** [comment]
Damnit I forgot the stupid combat update checker again... It wont harm your server it will just be a bit spammy in the console. I will have an update for this out soon once I get all the other bugs resolved.

**Comment by Mayr3D** [comment]
is not just spaming is removing the items when i changed world

**Comment by RockinChaos** [comment]
It only removes the items if you have the option turned on?
