### ISSUE TITLE
Clear Item on join

### ISSUE THREAD

**Issue by Mayr3D** [RockinChaos/ItemJoin#76]
[16:00:34] [Server thread/WARN]: [ItemJoin] Task #1117 for ItemJoin v3.8 generated an exception
java.lang.NoSuchMethodError: org.bukkit.inventory.PlayerInventory.getItemInOffHand()Lorg/bukkit/inventory/ItemStack;
	at me.RockinChaos.itemjoin.utils.CheckItem.setOffhand(CheckItem.java:196) ~[?:?]
	at me.RockinChaos.itemjoin.Listeners.JoinItem.JoinItem.clearItemJoinItems(JoinItem.java:103) ~[?:?]
	at me.RockinChaos.itemjoin.Listeners.JoinItem.JoinItem.setClearItems(JoinItem.java:82) ~[?:?]
	at me.RockinChaos.itemjoin.Listeners.JoinItem.JoinItem$1.run(JoinItem.java:42) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[Spigot-1.8.8-R0.1.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [Spigot-1.8.8-R0.1.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [Spigot-1.8.8-R0.1.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [Spigot-1.8.8-R0.1.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [Spigot-1.8.8-R0.1.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [Spigot-1.8.8-R0.1.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]

**Comment by RockinChaos** [comment]
Fixed for v3.9. Forgot to add the combat update checker to the clear items for offhand. Update will be out soon.

**Comment by Mayr3D** [comment]
I;m waiting :D

**Comment by Mayr3D** [comment]
can you do a favor to me if u can ?
there is a plugin called itemframe clicker the auther seems dead
all i want is cooldown in seconds, cuz he made it only in minutes -_-:(
also feature of changing sound while clicking :!

**Comment by Mayr3D** [comment]
We still waiting for 3.9 :!

**Comment by RockinChaos** [comment]
Sorry im getting your messages, I have been in the hospital with health related issues a lot this month but im getting back on my feet. I am working as much as I can to get this release out for you.

**Comment by RockinChaos** [comment]
ItemJoin v3.9 has been released and fixes this issue.
You can download it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=139837
If you have anymore problems feel free to open another bug report.
